@ECHO OFF

@CD /d "%~dp0"

SET "MAP01=bamap_aw01_04"
SET "MAP02=bamap_dc01_4"
SET "MAP03=bamap_dc02_4"
SET "MAP04=bamap_dc03_3"
SET "MAP05=bamap_dc04_3"
SET "MAP06=bamap_dc05_2"
SET "MAP07=bamap_dc05_3"
SET "MAP08=bamap_dc06_4"
SET "MAP09=bamap_dc07_4"
SET "MAP10=bamap_dc08_4"
SET "MAP11=bamap_dc10_4"
SET "MAP12=bamap_dc11_4"
SET "MAP13=bamap_ew01_4"
SET "MAP14=bamap_ew03_04"
SET "MAP15=bamap_ew05_04"
SET "MAP16=bamap_ew06_04"
SET "MAP17=bamap_ew07_04"
SET "MAP18=bamap_ew08_04"
SET "MAP19=bamap_ew09_03"
SET "MAP20=bamap_ew10_06"
SET "MAP21=bamap_ew11_05"
SET "MAP22=bamap_jf01_4"
SET "MAP23=bamap_jf03_6"
SET "MAP24=bamap_kk03_3"
SET "MAP25=bamap_rh01_4"
SET "MAP26=bamap_sb01_4"
SET "MAP27=EAMAP_SB05_4"
SET "MAP28=map_mp_2_bass1"
SET "MAP29=map_mp_2_black1"
SET "MAP30=map_mp_2_black2"
SET "MAP31=map_mp_2_black3"
SET "MAP32=map_mp_2_black4"
SET "MAP33=map_mp_2_black5"
SET "MAP34=map_mp_2_black6"
SET "MAP35=map_mp_2_black7"
SET "MAP36=map_mp_2_black8"
SET "MAP37=map_mp_2_black9"
SET "MAP38=map_mp_2_black10"
SET "MAP39=map_mp_2_black11"
SET "MAP40=map_mp_2_black12"
SET "MAP41=map_mp_2_chuck1"
SET "MAP42=map_mp_2_simon"
SET "MAP43=map_mp_2_will1"
SET "MAP44=map_mp_3_black1"
SET "MAP45=map_mp_3_black2"
SET "MAP46=map_mp_4_bass"
SET "MAP47=map_mp_4_bender"
SET "MAP48=map_mp_4_black1"
SET "MAP49=map_mp_4_black5"
SET "MAP50=map_mp_4_black6"
SET "MAP51=map_mp_4_chuck1"
SET "MAP52=map_mp_4_chuck2"
SET "MAP53=map_mp_4_rao"
SET "MAP54=map_mp_4_ssmith_01"
SET "MAP55=map_mp_5_black1"
SET "MAP56=map_mp_6_black1"
SET "MAP57=map_mp_6_black2"
SET "MAP58=map_mp_6_hayes"
SET "MAP59=map_mp_8_bass"
SET "MAP60=map_mp_8_black1"
SET "MAP61=MAP_MP_2_BLACK2_redzoned"
SET "MAP62=MAP_MP_2_BLACK7_redzoned"
SET "MAP63=MAP_MP_2_BLACK11_redzoned"
SET "MAP64=MAP_MP_2_SIMON_B"
SET "MAP65=EAMAP_SB01_3"
SET "MAP66=EAMAP_SB02_3"
SET "MAP67=EAMAP_SB03_3"
SET "MAP68=EAMAP_SB04_3"

SET VAR1=INFONLY
SET VAR2=LONEWOLF
SET VAR3=NOAIR
SET VAR4=NOSW
SET VAR5=NOSW_NOAIR
SET VAR6=NOSW_NOUP
SET VAR7=TNKSONLY

SET "MAPDIR=C:\Users\Jenkins\AppData\Roaming\Command & Conquer 3 Kane's Wrath\Maps"


REN "Seaport Smackdown [%VAR1%]" "bamap_aw01_04_%VAR1%"
REN "Grasslands Landgrab [%VAR1%]" "bamap_dc01_4_%VAR1%"
REN "Badlands [%VAR1%]" "bamap_dc02_4_%VAR1%"
REN "Desolation [%VAR1%]" "bamap_dc03_3_%VAR1%"
REN "End of the Line [%VAR1%]" "bamap_dc04_3_%VAR1%"
REN "Tournament Decision [%VAR1%]" "bamap_dc05_2_%VAR1%"
REN "Split Decision [%VAR1%]" "bamap_dc05_3_%VAR1%"
REN "Arid Remains [%VAR1%]" "bamap_dc06_4_%VAR1%"
REN "Mountains of Madness [%VAR1%]" "bamap_dc07_4_%VAR1%"
REN "Crosstown Conflict [%VAR1%]" "bamap_dc08_4_%VAR1%"
REN "Murderers Row [%VAR1%]" "bamap_dc10_4_%VAR1%"
REN "Empire City [%VAR1%]" "bamap_dc11_4_%VAR1%"
REN "Unsound Investment [%VAR1%]" "bamap_ew01_4_%VAR1%"
REN "Oasis Onslaught [%VAR1%]" "bamap_ew03_04_%VAR1%"
REN "Safety Nest [%VAR1%]" "bamap_ew05_04_%VAR1%"
REN "Shell Shocked [%VAR1%]" "bamap_ew06_04_%VAR1%"
REN "Urban Blight [%VAR1%]" "bamap_ew07_04_%VAR1%"
REN "Eastern Promises [%VAR1%]" "bamap_ew08_04_%VAR1%"
REN "Suburban Slaughterhouse [%VAR1%]" "bamap_ew09_03_%VAR1%"
REN "Tiberium Wasteland [%VAR1%]" "bamap_ew10_06_%VAR1%"
REN "Isthmus of Insanity [%VAR1%]" "bamap_ew11_05_%VAR1%"
REN "Dockside Devastation [%VAR1%]" "bamap_jf01_4_%VAR1%"
REN "Dark Waters [%VAR1%]" "bamap_jf03_6_%VAR1%"
REN "Tundra Triangle [%VAR1%]" "bamap_kk03_3_%VAR1%"
REN "Heaven and Hell [%VAR1%]" "bamap_rh01_4_%VAR1%"
REN "Missed Opportunity [%VAR1%]" "bamap_sb01_4_%VAR1%"
REN "Craters of Camden [%VAR1%]" "eamap_sb05_4_%VAR1%"
REN "Tournament Dustbowl [%VAR1%]" "map_mp_2_bass1_%VAR1%"
REN "Tournament Desert Redux [%VAR1%]" "map_mp_2_black1_%VAR1%"
REN "Deadly Sertao [%VAR1%]" "map_mp_2_black10_%VAR1%"
REN "Top Gun [%VAR1%]" "map_mp_2_black11_%VAR1%"
REN "Schlachtfeld Stuttgart [%VAR1%]" "map_mp_2_black12_%VAR1%"
REN "Tournament Arena [%VAR1%]" "map_mp_2_black2_%VAR1%"
REN "Barstow Badlands [%VAR1%]" "map_mp_2_black3_%VAR1%"
REN "Ground Zero [%VAR1%]" "map_mp_2_black4_%VAR1%"
REN "Small Town USA [%VAR1%]" "map_mp_2_black5_%VAR1%"
REN "Black's Big Battle [%VAR1%]" "map_mp_2_black6_%VAR1%"
REN "Tournament Tower [%VAR1%]" "map_mp_2_black7_%VAR1%"
REN "Tiber River Valley [%VAR1%]" "map_mp_2_black8_%VAR1%"
REN "Pipeline Problems [%VAR1%]" "map_mp_2_black9_%VAR1%"
REN "Tournament Coastline [%VAR1%]" "map_mp_2_chuck1_%VAR1%"
REN "Riverside Rumble [%VAR1%]" "map_mp_2_simon_%VAR1%"
REN "Tournament Rift [%VAR1%]" "map_mp_2_will1_%VAR1%"
REN "Unfair Advantage [%VAR1%]" "map_mp_3_black1_%VAR1%"
REN "Triple Threat [%VAR1%]" "map_mp_3_black2_%VAR1%"
REN "Downtown Dustbowl [%VAR1%]" "map_mp_4_bass_%VAR1%"
REN "The Battle for Middle Egypt [%VAR1%]" "map_mp_4_bender_%VAR1%"
REN "Crater of Carnage [%VAR1%]" "map_mp_4_black1_%VAR1%"
REN "Death Valley [%VAR1%]" "map_mp_4_black5_%VAR1%"
REN "Backwater Brawl [%VAR1%]" "map_mp_4_black6_%VAR1%"
REN "Coastline Chaos [%VAR1%]" "map_mp_4_chuck1_%VAR1%"
REN "Wrecktropolis [%VAR1%]" "map_mp_4_chuck2_%VAR1%"
REN "Redzone Rampage [%VAR1%]" "map_mp_4_rao_%VAR1%"
REN "Frontier Fracas [%VAR1%]" "map_mp_4_ssmith_01_%VAR1%"
REN "Tiberium Gardens III [%VAR1%]" "map_mp_5_black1_%VAR1%"
REN "Black's Bigger Battle [%VAR1%]" "map_mp_6_black1_%VAR1%"
REN "Six Shooter Showdown [%VAR1%]" "map_mp_6_black2_%VAR1%"
REN "Dead Six [%VAR1%]" "map_mp_6_hayes_%VAR1%"
REN "The Rocktagon [%VAR1%]" "map_mp_8_bass_%VAR1%"
REN "Bordertown Beatdown [%VAR1%]" "map_mp_8_black1_%VAR1%"
REN "Decrepit Arena [%VAR1%]" "map_mp_2_black2_redzoned_%VAR1%"
REN "Blighted Tower [%VAR1%]" "map_mp_2_black7_redzoned_%VAR1%"
REN "Gunship Gauntlet [%VAR1%]" "map_mp_2_black11_redzoned_%VAR1%"
REN "Ruined River [%VAR1%]" "map_mp_2_simon_b_%VAR1%"
REN "Cut 3player Map #1 [%VAR1%]" "EAMAP_SB01_3_%VAR1%"
REN "Cut 3player Map #2 [%VAR1%]" "EAMAP_SB02_3_%VAR1%"
REN "Cut 3player Map #3 [%VAR1%]" "EAMAP_SB03_3_%VAR1%"
REN "Cut 3player Map #4 [%VAR1%]" "EAMAP_SB04_3_%VAR1%"

REN "Seaport Smackdown [%VAR2%]" "bamap_aw01_04_%VAR2%"
REN "Grasslands Landgrab [%VAR2%]" "bamap_dc01_4_%VAR2%"
REN "Badlands [%VAR2%]" "bamap_dc02_4_%VAR2%"
REN "Desolation [%VAR2%]" "bamap_dc03_3_%VAR2%"
REN "End of the Line [%VAR2%]" "bamap_dc04_3_%VAR2%"
REN "Tournament Decision [%VAR2%]" "bamap_dc05_2_%VAR2%"
REN "Split Decision [%VAR2%]" "bamap_dc05_3_%VAR2%"
REN "Arid Remains [%VAR2%]" "bamap_dc06_4_%VAR2%"
REN "Mountains of Madness [%VAR2%]" "bamap_dc07_4_%VAR2%"
REN "Crosstown Conflict [%VAR2%]" "bamap_dc08_4_%VAR2%"
REN "Murderers Row [%VAR2%]" "bamap_dc10_4_%VAR2%"
REN "Empire City [%VAR2%]" "bamap_dc11_4_%VAR2%"
REN "Unsound Investment [%VAR2%]" "bamap_ew01_4_%VAR2%"
REN "Oasis Onslaught [%VAR2%]" "bamap_ew03_04_%VAR2%"
REN "Safety Nest [%VAR2%]" "bamap_ew05_04_%VAR2%"
REN "Shell Shocked [%VAR2%]" "bamap_ew06_04_%VAR2%"
REN "Urban Blight [%VAR2%]" "bamap_ew07_04_%VAR2%"
REN "Eastern Promises [%VAR2%]" "bamap_ew08_04_%VAR2%"
REN "Suburban Slaughterhouse [%VAR2%]" "bamap_ew09_03_%VAR2%"
REN "Tiberium Wasteland [%VAR2%]" "bamap_ew10_06_%VAR2%"
REN "Isthmus of Insanity [%VAR2%]" "bamap_ew11_05_%VAR2%"
REN "Dockside Devastation [%VAR2%]" "bamap_jf01_4_%VAR2%"
REN "Dark Waters [%VAR2%]" "bamap_jf03_6_%VAR2%"
REN "Tundra Triangle [%VAR2%]" "bamap_kk03_3_%VAR2%"
REN "Heaven and Hell [%VAR2%]" "bamap_rh01_4_%VAR2%"
REN "Missed Opportunity [%VAR2%]" "bamap_sb01_4_%VAR2%"
REN "Craters of Camden [%VAR2%]" "eamap_sb05_4_%VAR2%"
REN "Tournament Dustbowl [%VAR2%]" "map_mp_2_bass1_%VAR2%"
REN "Tournament Desert Redux [%VAR2%]" "map_mp_2_black1_%VAR2%"
REN "Deadly Sertao [%VAR2%]" "map_mp_2_black10_%VAR2%"
REN "Top Gun [%VAR2%]" "map_mp_2_black11_%VAR2%"
REN "Schlachtfeld Stuttgart [%VAR2%]" "map_mp_2_black12_%VAR2%"
REN "Tournament Arena [%VAR2%]" "map_mp_2_black2_%VAR2%"
REN "Barstow Badlands [%VAR2%]" "map_mp_2_black3_%VAR2%"
REN "Ground Zero [%VAR2%]" "map_mp_2_black4_%VAR2%"
REN "Small Town USA [%VAR2%]" "map_mp_2_black5_%VAR2%"
REN "Black's Big Battle [%VAR2%]" "map_mp_2_black6_%VAR2%"
REN "Tournament Tower [%VAR2%]" "map_mp_2_black7_%VAR2%"
REN "Tiber River Valley [%VAR2%]" "map_mp_2_black8_%VAR2%"
REN "Pipeline Problems [%VAR2%]" "map_mp_2_black9_%VAR2%"
REN "Tournament Coastline [%VAR2%]" "map_mp_2_chuck1_%VAR2%"
REN "Riverside Rumble [%VAR2%]" "map_mp_2_simon_%VAR2%"
REN "Tournament Rift [%VAR2%]" "map_mp_2_will1_%VAR2%"
REN "Unfair Advantage [%VAR2%]" "map_mp_3_black1_%VAR2%"
REN "Triple Threat [%VAR2%]" "map_mp_3_black2_%VAR2%"
REN "Downtown Dustbowl [%VAR2%]" "map_mp_4_bass_%VAR2%"
REN "The Battle for Middle Egypt [%VAR2%]" "map_mp_4_bender_%VAR2%"
REN "Crater of Carnage [%VAR2%]" "map_mp_4_black1_%VAR2%"
REN "Death Valley [%VAR2%]" "map_mp_4_black5_%VAR2%"
REN "Backwater Brawl [%VAR2%]" "map_mp_4_black6_%VAR2%"
REN "Coastline Chaos [%VAR2%]" "map_mp_4_chuck1_%VAR2%"
REN "Wrecktropolis [%VAR2%]" "map_mp_4_chuck2_%VAR2%"
REN "Redzone Rampage [%VAR2%]" "map_mp_4_rao_%VAR2%"
REN "Frontier Fracas [%VAR2%]" "map_mp_4_ssmith_01_%VAR2%"
REN "Tiberium Gardens III [%VAR2%]" "map_mp_5_black1_%VAR2%"
REN "Black's Bigger Battle [%VAR2%]" "map_mp_6_black1_%VAR2%"
REN "Six Shooter Showdown [%VAR2%]" "map_mp_6_black2_%VAR2%"
REN "Dead Six [%VAR2%]" "map_mp_6_hayes_%VAR2%"
REN "The Rocktagon [%VAR2%]" "map_mp_8_bass_%VAR2%"
REN "Bordertown Beatdown [%VAR2%]" "map_mp_8_black1_%VAR2%"
REN "Decrepit Arena [%VAR2%]" "map_mp_2_black2_redzoned_%VAR2%"
REN "Blighted Tower [%VAR2%]" "map_mp_2_black7_redzoned_%VAR2%"
REN "Gunship Gauntlet [%VAR2%]" "map_mp_2_black11_redzoned_%VAR2%"
REN "Ruined River [%VAR2%]" "map_mp_2_simon_b_%VAR2%"
REN "Cut 3player Map #1 [%VAR2%]" "EAMAP_SB01_3_%VAR2%"
REN "Cut 3player Map #2 [%VAR2%]" "EAMAP_SB02_3_%VAR2%"
REN "Cut 3player Map #3 [%VAR2%]" "EAMAP_SB03_3_%VAR2%"
REN "Cut 3player Map #4 [%VAR2%]" "EAMAP_SB04_3_%VAR2%"

REN "Seaport Smackdown [%VAR3%]" "bamap_aw01_04_%VAR3%"
REN "Grasslands Landgrab [%VAR3%]" "bamap_dc01_4_%VAR3%"
REN "Badlands [%VAR3%]" "bamap_dc02_4_%VAR3%"
REN "Desolation [%VAR3%]" "bamap_dc03_3_%VAR3%"
REN "End of the Line [%VAR3%]" "bamap_dc04_3_%VAR3%"
REN "Tournament Decision [%VAR3%]" "bamap_dc05_2_%VAR3%"
REN "Split Decision [%VAR3%]" "bamap_dc05_3_%VAR3%"
REN "Arid Remains [%VAR3%]" "bamap_dc06_4_%VAR3%"
REN "Mountains of Madness [%VAR3%]" "bamap_dc07_4_%VAR3%"
REN "Crosstown Conflict [%VAR3%]" "bamap_dc08_4_%VAR3%"
REN "Murderers Row [%VAR3%]" "bamap_dc10_4_%VAR3%"
REN "Empire City [%VAR3%]" "bamap_dc11_4_%VAR3%"
REN "Unsound Investment [%VAR3%]" "bamap_ew01_4_%VAR3%"
REN "Oasis Onslaught [%VAR3%]" "bamap_ew03_04_%VAR3%"
REN "Safety Nest [%VAR3%]" "bamap_ew05_04_%VAR3%"
REN "Shell Shocked [%VAR3%]" "bamap_ew06_04_%VAR3%"
REN "Urban Blight [%VAR3%]" "bamap_ew07_04_%VAR3%"
REN "Eastern Promises [%VAR3%]" "bamap_ew08_04_%VAR3%"
REN "Suburban Slaughterhouse [%VAR3%]" "bamap_ew09_03_%VAR3%"
REN "Tiberium Wasteland [%VAR3%]" "bamap_ew10_06_%VAR3%"
REN "Isthmus of Insanity [%VAR3%]" "bamap_ew11_05_%VAR3%"
REN "Dockside Devastation [%VAR3%]" "bamap_jf01_4_%VAR3%"
REN "Dark Waters [%VAR3%]" "bamap_jf03_6_%VAR3%"
REN "Tundra Triangle [%VAR3%]" "bamap_kk03_3_%VAR3%"
REN "Heaven and Hell [%VAR3%]" "bamap_rh01_4_%VAR3%"
REN "Missed Opportunity [%VAR3%]" "bamap_sb01_4_%VAR3%"
REN "Craters of Camden [%VAR3%]" "eamap_sb05_4_%VAR3%"
REN "Tournament Dustbowl [%VAR3%]" "map_mp_2_bass1_%VAR3%"
REN "Tournament Desert Redux [%VAR3%]" "map_mp_2_black1_%VAR3%"
REN "Deadly Sertao [%VAR3%]" "map_mp_2_black10_%VAR3%"
REN "Top Gun [%VAR3%]" "map_mp_2_black11_%VAR3%"
REN "Schlachtfeld Stuttgart [%VAR3%]" "map_mp_2_black12_%VAR3%"
REN "Tournament Arena [%VAR3%]" "map_mp_2_black2_%VAR3%"
REN "Barstow Badlands [%VAR3%]" "map_mp_2_black3_%VAR3%"
REN "Ground Zero [%VAR3%]" "map_mp_2_black4_%VAR3%"
REN "Small Town USA [%VAR3%]" "map_mp_2_black5_%VAR3%"
REN "Black's Big Battle [%VAR3%]" "map_mp_2_black6_%VAR3%"
REN "Tournament Tower [%VAR3%]" "map_mp_2_black7_%VAR3%"
REN "Tiber River Valley [%VAR3%]" "map_mp_2_black8_%VAR3%"
REN "Pipeline Problems [%VAR3%]" "map_mp_2_black9_%VAR3%"
REN "Tournament Coastline [%VAR3%]" "map_mp_2_chuck1_%VAR3%"
REN "Riverside Rumble [%VAR3%]" "map_mp_2_simon_%VAR3%"
REN "Tournament Rift [%VAR3%]" "map_mp_2_will1_%VAR3%"
REN "Unfair Advantage [%VAR3%]" "map_mp_3_black1_%VAR3%"
REN "Triple Threat [%VAR3%]" "map_mp_3_black2_%VAR3%"
REN "Downtown Dustbowl [%VAR3%]" "map_mp_4_bass_%VAR3%"
REN "The Battle for Middle Egypt [%VAR3%]" "map_mp_4_bender_%VAR3%"
REN "Crater of Carnage [%VAR3%]" "map_mp_4_black1_%VAR3%"
REN "Death Valley [%VAR3%]" "map_mp_4_black5_%VAR3%"
REN "Backwater Brawl [%VAR3%]" "map_mp_4_black6_%VAR3%"
REN "Coastline Chaos [%VAR3%]" "map_mp_4_chuck1_%VAR3%"
REN "Wrecktropolis [%VAR3%]" "map_mp_4_chuck2_%VAR3%"
REN "Redzone Rampage [%VAR3%]" "map_mp_4_rao_%VAR3%"
REN "Frontier Fracas [%VAR3%]" "map_mp_4_ssmith_01_%VAR3%"
REN "Tiberium Gardens III [%VAR3%]" "map_mp_5_black1_%VAR3%"
REN "Black's Bigger Battle [%VAR3%]" "map_mp_6_black1_%VAR3%"
REN "Six Shooter Showdown [%VAR3%]" "map_mp_6_black2_%VAR3%"
REN "Dead Six [%VAR3%]" "map_mp_6_hayes_%VAR3%"
REN "The Rocktagon [%VAR3%]" "map_mp_8_bass_%VAR3%"
REN "Bordertown Beatdown [%VAR3%]" "map_mp_8_black1_%VAR3%"
REN "Decrepit Arena [%VAR3%]" "map_mp_2_black2_redzoned_%VAR3%"
REN "Blighted Tower [%VAR3%]" "map_mp_2_black7_redzoned_%VAR3%"
REN "Gunship Gauntlet [%VAR3%]" "map_mp_2_black11_redzoned_%VAR3%"
REN "Ruined River [%VAR3%]" "map_mp_2_simon_b_%VAR3%"
REN "Cut 3player Map #1 [%VAR3%]" "EAMAP_SB01_3_%VAR3%"
REN "Cut 3player Map #2 [%VAR3%]" "EAMAP_SB02_3_%VAR3%"
REN "Cut 3player Map #3 [%VAR3%]" "EAMAP_SB03_3_%VAR3%"
REN "Cut 3player Map #4 [%VAR3%]" "EAMAP_SB04_3_%VAR3%"

REN "Seaport Smackdown [%VAR4%]" "bamap_aw01_04_%VAR4%"
REN "Grasslands Landgrab [%VAR4%]" "bamap_dc01_4_%VAR4%"
REN "Badlands [%VAR4%]" "bamap_dc02_4_%VAR4%"
REN "Desolation [%VAR4%]" "bamap_dc03_3_%VAR4%"
REN "End of the Line [%VAR4%]" "bamap_dc04_3_%VAR4%"
REN "Tournament Decision [%VAR4%]" "bamap_dc05_2_%VAR4%"
REN "Split Decision [%VAR4%]" "bamap_dc05_3_%VAR4%"
REN "Arid Remains [%VAR4%]" "bamap_dc06_4_%VAR4%"
REN "Mountains of Madness [%VAR4%]" "bamap_dc07_4_%VAR4%"
REN "Crosstown Conflict [%VAR4%]" "bamap_dc08_4_%VAR4%"
REN "Murderers Row [%VAR4%]" "bamap_dc10_4_%VAR4%"
REN "Empire City [%VAR4%]" "bamap_dc11_4_%VAR4%"
REN "Unsound Investment [%VAR4%]" "bamap_ew01_4_%VAR4%"
REN "Oasis Onslaught [%VAR4%]" "bamap_ew03_04_%VAR4%"
REN "Safety Nest [%VAR4%]" "bamap_ew05_04_%VAR4%"
REN "Shell Shocked [%VAR4%]" "bamap_ew06_04_%VAR4%"
REN "Urban Blight [%VAR4%]" "bamap_ew07_04_%VAR4%"
REN "Eastern Promises [%VAR4%]" "bamap_ew08_04_%VAR4%"
REN "Suburban Slaughterhouse [%VAR4%]" "bamap_ew09_03_%VAR4%"
REN "Tiberium Wasteland [%VAR4%]" "bamap_ew10_06_%VAR4%"
REN "Isthmus of Insanity [%VAR4%]" "bamap_ew11_05_%VAR4%"
REN "Dockside Devastation [%VAR4%]" "bamap_jf01_4_%VAR4%"
REN "Dark Waters [%VAR4%]" "bamap_jf03_6_%VAR4%"
REN "Tundra Triangle [%VAR4%]" "bamap_kk03_3_%VAR4%"
REN "Heaven and Hell [%VAR4%]" "bamap_rh01_4_%VAR4%"
REN "Missed Opportunity [%VAR4%]" "bamap_sb01_4_%VAR4%"
REN "Craters of Camden [%VAR4%]" "eamap_sb05_4_%VAR4%"
REN "Tournament Dustbowl [%VAR4%]" "map_mp_2_bass1_%VAR4%"
REN "Tournament Desert Redux [%VAR4%]" "map_mp_2_black1_%VAR4%"
REN "Deadly Sertao [%VAR4%]" "map_mp_2_black10_%VAR4%"
REN "Top Gun [%VAR4%]" "map_mp_2_black11_%VAR4%"
REN "Schlachtfeld Stuttgart [%VAR4%]" "map_mp_2_black12_%VAR4%"
REN "Tournament Arena [%VAR4%]" "map_mp_2_black2_%VAR4%"
REN "Barstow Badlands [%VAR4%]" "map_mp_2_black3_%VAR4%"
REN "Ground Zero [%VAR4%]" "map_mp_2_black4_%VAR4%"
REN "Small Town USA [%VAR4%]" "map_mp_2_black5_%VAR4%"
REN "Black's Big Battle [%VAR4%]" "map_mp_2_black6_%VAR4%"
REN "Tournament Tower [%VAR4%]" "map_mp_2_black7_%VAR4%"
REN "Tiber River Valley [%VAR4%]" "map_mp_2_black8_%VAR4%"
REN "Pipeline Problems [%VAR4%]" "map_mp_2_black9_%VAR4%"
REN "Tournament Coastline [%VAR4%]" "map_mp_2_chuck1_%VAR4%"
REN "Riverside Rumble [%VAR4%]" "map_mp_2_simon_%VAR4%"
REN "Tournament Rift [%VAR4%]" "map_mp_2_will1_%VAR4%"
REN "Unfair Advantage [%VAR4%]" "map_mp_3_black1_%VAR4%"
REN "Triple Threat [%VAR4%]" "map_mp_3_black2_%VAR4%"
REN "Downtown Dustbowl [%VAR4%]" "map_mp_4_bass_%VAR4%"
REN "The Battle for Middle Egypt [%VAR4%]" "map_mp_4_bender_%VAR4%"
REN "Crater of Carnage [%VAR4%]" "map_mp_4_black1_%VAR4%"
REN "Death Valley [%VAR4%]" "map_mp_4_black5_%VAR4%"
REN "Backwater Brawl [%VAR4%]" "map_mp_4_black6_%VAR4%"
REN "Coastline Chaos [%VAR4%]" "map_mp_4_chuck1_%VAR4%"
REN "Wrecktropolis [%VAR4%]" "map_mp_4_chuck2_%VAR4%"
REN "Redzone Rampage [%VAR4%]" "map_mp_4_rao_%VAR4%"
REN "Frontier Fracas [%VAR4%]" "map_mp_4_ssmith_01_%VAR4%"
REN "Tiberium Gardens III [%VAR4%]" "map_mp_5_black1_%VAR4%"
REN "Black's Bigger Battle [%VAR4%]" "map_mp_6_black1_%VAR4%"
REN "Six Shooter Showdown [%VAR4%]" "map_mp_6_black2_%VAR4%"
REN "Dead Six [%VAR4%]" "map_mp_6_hayes_%VAR4%"
REN "The Rocktagon [%VAR4%]" "map_mp_8_bass_%VAR4%"
REN "Bordertown Beatdown [%VAR4%]" "map_mp_8_black1_%VAR4%"
REN "Decrepit Arena [%VAR4%]" "map_mp_2_black2_redzoned_%VAR4%"
REN "Blighted Tower [%VAR4%]" "map_mp_2_black7_redzoned_%VAR4%"
REN "Gunship Gauntlet [%VAR4%]" "map_mp_2_black11_redzoned_%VAR4%"
REN "Ruined River [%VAR4%]" "map_mp_2_simon_b_%VAR4%"
REN "Cut 3player Map #1 [%VAR4%]" "EAMAP_SB01_3_%VAR4%"
REN "Cut 3player Map #2 [%VAR4%]" "EAMAP_SB02_3_%VAR4%"
REN "Cut 3player Map #3 [%VAR4%]" "EAMAP_SB03_3_%VAR4%"
REN "Cut 3player Map #4 [%VAR4%]" "EAMAP_SB04_3_%VAR4%"

REN "Seaport Smackdown [%VAR5%]" "bamap_aw01_04_%VAR5%"
REN "Grasslands Landgrab [%VAR5%]" "bamap_dc01_4_%VAR5%"
REN "Badlands [%VAR5%]" "bamap_dc02_4_%VAR5%"
REN "Desolation [%VAR5%]" "bamap_dc03_3_%VAR5%"
REN "End of the Line [%VAR5%]" "bamap_dc04_3_%VAR5%"
REN "Tournament Decision [%VAR5%]" "bamap_dc05_2_%VAR5%"
REN "Split Decision [%VAR5%]" "bamap_dc05_3_%VAR5%"
REN "Arid Remains [%VAR5%]" "bamap_dc06_4_%VAR5%"
REN "Mountains of Madness [%VAR5%]" "bamap_dc07_4_%VAR5%"
REN "Crosstown Conflict [%VAR5%]" "bamap_dc08_4_%VAR5%"
REN "Murderers Row [%VAR5%]" "bamap_dc10_4_%VAR5%"
REN "Empire City [%VAR5%]" "bamap_dc11_4_%VAR5%"
REN "Unsound Investment [%VAR5%]" "bamap_ew01_4_%VAR5%"
REN "Oasis Onslaught [%VAR5%]" "bamap_ew03_04_%VAR5%"
REN "Safety Nest [%VAR5%]" "bamap_ew05_04_%VAR5%"
REN "Shell Shocked [%VAR5%]" "bamap_ew06_04_%VAR5%"
REN "Urban Blight [%VAR5%]" "bamap_ew07_04_%VAR5%"
REN "Eastern Promises [%VAR5%]" "bamap_ew08_04_%VAR5%"
REN "Suburban Slaughterhouse [%VAR5%]" "bamap_ew09_03_%VAR5%"
REN "Tiberium Wasteland [%VAR5%]" "bamap_ew10_06_%VAR5%"
REN "Isthmus of Insanity [%VAR5%]" "bamap_ew11_05_%VAR5%"
REN "Dockside Devastation [%VAR5%]" "bamap_jf01_4_%VAR5%"
REN "Dark Waters [%VAR5%]" "bamap_jf03_6_%VAR5%"
REN "Tundra Triangle [%VAR5%]" "bamap_kk03_3_%VAR5%"
REN "Heaven and Hell [%VAR5%]" "bamap_rh01_4_%VAR5%"
REN "Missed Opportunity [%VAR5%]" "bamap_sb01_4_%VAR5%"
REN "Craters of Camden [%VAR5%]" "eamap_sb05_4_%VAR5%"
REN "Tournament Dustbowl [%VAR5%]" "map_mp_2_bass1_%VAR5%"
REN "Tournament Desert Redux [%VAR5%]" "map_mp_2_black1_%VAR5%"
REN "Deadly Sertao [%VAR5%]" "map_mp_2_black10_%VAR5%"
REN "Top Gun [%VAR5%]" "map_mp_2_black11_%VAR5%"
REN "Schlachtfeld Stuttgart [%VAR5%]" "map_mp_2_black12_%VAR5%"
REN "Tournament Arena [%VAR5%]" "map_mp_2_black2_%VAR5%"
REN "Barstow Badlands [%VAR5%]" "map_mp_2_black3_%VAR5%"
REN "Ground Zero [%VAR5%]" "map_mp_2_black4_%VAR5%"
REN "Small Town USA [%VAR5%]" "map_mp_2_black5_%VAR5%"
REN "Black's Big Battle [%VAR5%]" "map_mp_2_black6_%VAR5%"
REN "Tournament Tower [%VAR5%]" "map_mp_2_black7_%VAR5%"
REN "Tiber River Valley [%VAR5%]" "map_mp_2_black8_%VAR5%"
REN "Pipeline Problems [%VAR5%]" "map_mp_2_black9_%VAR5%"
REN "Tournament Coastline [%VAR5%]" "map_mp_2_chuck1_%VAR5%"
REN "Riverside Rumble [%VAR5%]" "map_mp_2_simon_%VAR5%"
REN "Tournament Rift [%VAR5%]" "map_mp_2_will1_%VAR5%"
REN "Unfair Advantage [%VAR5%]" "map_mp_3_black1_%VAR5%"
REN "Triple Threat [%VAR5%]" "map_mp_3_black2_%VAR5%"
REN "Downtown Dustbowl [%VAR5%]" "map_mp_4_bass_%VAR5%"
REN "The Battle for Middle Egypt [%VAR5%]" "map_mp_4_bender_%VAR5%"
REN "Crater of Carnage [%VAR5%]" "map_mp_4_black1_%VAR5%"
REN "Death Valley [%VAR5%]" "map_mp_4_black5_%VAR5%"
REN "Backwater Brawl [%VAR5%]" "map_mp_4_black6_%VAR5%"
REN "Coastline Chaos [%VAR5%]" "map_mp_4_chuck1_%VAR5%"
REN "Wrecktropolis [%VAR5%]" "map_mp_4_chuck2_%VAR5%"
REN "Redzone Rampage [%VAR5%]" "map_mp_4_rao_%VAR5%"
REN "Frontier Fracas [%VAR5%]" "map_mp_4_ssmith_01_%VAR5%"
REN "Tiberium Gardens III [%VAR5%]" "map_mp_5_black1_%VAR5%"
REN "Black's Bigger Battle [%VAR5%]" "map_mp_6_black1_%VAR5%"
REN "Six Shooter Showdown [%VAR5%]" "map_mp_6_black2_%VAR5%"
REN "Dead Six [%VAR5%]" "map_mp_6_hayes_%VAR5%"
REN "The Rocktagon [%VAR5%]" "map_mp_8_bass_%VAR5%"
REN "Bordertown Beatdown [%VAR5%]" "map_mp_8_black1_%VAR5%"
REN "Decrepit Arena [%VAR5%]" "map_mp_2_black2_redzoned_%VAR5%"
REN "Blighted Tower [%VAR5%]" "map_mp_2_black7_redzoned_%VAR5%"
REN "Gunship Gauntlet [%VAR5%]" "map_mp_2_black11_redzoned_%VAR5%"
REN "Ruined River [%VAR5%]" "map_mp_2_simon_b_%VAR5%"
REN "Cut 3player Map #1 [%VAR5%]" "EAMAP_SB01_3_%VAR5%"
REN "Cut 3player Map #2 [%VAR5%]" "EAMAP_SB02_3_%VAR5%"
REN "Cut 3player Map #3 [%VAR5%]" "EAMAP_SB03_3_%VAR5%"
REN "Cut 3player Map #4 [%VAR5%]" "EAMAP_SB04_3_%VAR5%"

REN "Seaport Smackdown [%VAR6%]" "bamap_aw01_04_%VAR6%"
REN "Grasslands Landgrab [%VAR6%]" "bamap_dc01_4_%VAR6%"
REN "Badlands [%VAR6%]" "bamap_dc02_4_%VAR6%"
REN "Desolation [%VAR6%]" "bamap_dc03_3_%VAR6%"
REN "End of the Line [%VAR6%]" "bamap_dc04_3_%VAR6%"
REN "Tournament Decision [%VAR6%]" "bamap_dc05_2_%VAR6%"
REN "Split Decision [%VAR6%]" "bamap_dc05_3_%VAR6%"
REN "Arid Remains [%VAR6%]" "bamap_dc06_4_%VAR6%"
REN "Mountains of Madness [%VAR6%]" "bamap_dc07_4_%VAR6%"
REN "Crosstown Conflict [%VAR6%]" "bamap_dc08_4_%VAR6%"
REN "Murderers Row [%VAR6%]" "bamap_dc10_4_%VAR6%"
REN "Empire City [%VAR6%]" "bamap_dc11_4_%VAR6%"
REN "Unsound Investment [%VAR6%]" "bamap_ew01_4_%VAR6%"
REN "Oasis Onslaught [%VAR6%]" "bamap_ew03_04_%VAR6%"
REN "Safety Nest [%VAR6%]" "bamap_ew05_04_%VAR6%"
REN "Shell Shocked [%VAR6%]" "bamap_ew06_04_%VAR6%"
REN "Urban Blight [%VAR6%]" "bamap_ew07_04_%VAR6%"
REN "Eastern Promises [%VAR6%]" "bamap_ew08_04_%VAR6%"
REN "Suburban Slaughterhouse [%VAR6%]" "bamap_ew09_03_%VAR6%"
REN "Tiberium Wasteland [%VAR6%]" "bamap_ew10_06_%VAR6%"
REN "Isthmus of Insanity [%VAR6%]" "bamap_ew11_05_%VAR6%"
REN "Dockside Devastation [%VAR6%]" "bamap_jf01_4_%VAR6%"
REN "Dark Waters [%VAR6%]" "bamap_jf03_6_%VAR6%"
REN "Tundra Triangle [%VAR6%]" "bamap_kk03_3_%VAR6%"
REN "Heaven and Hell [%VAR6%]" "bamap_rh01_4_%VAR6%"
REN "Missed Opportunity [%VAR6%]" "bamap_sb01_4_%VAR6%"
REN "Craters of Camden [%VAR6%]" "eamap_sb05_4_%VAR6%"
REN "Tournament Dustbowl [%VAR6%]" "map_mp_2_bass1_%VAR6%"
REN "Tournament Desert Redux [%VAR6%]" "map_mp_2_black1_%VAR6%"
REN "Deadly Sertao [%VAR6%]" "map_mp_2_black10_%VAR6%"
REN "Top Gun [%VAR6%]" "map_mp_2_black11_%VAR6%"
REN "Schlachtfeld Stuttgart [%VAR6%]" "map_mp_2_black12_%VAR6%"
REN "Tournament Arena [%VAR6%]" "map_mp_2_black2_%VAR6%"
REN "Barstow Badlands [%VAR6%]" "map_mp_2_black3_%VAR6%"
REN "Ground Zero [%VAR6%]" "map_mp_2_black4_%VAR6%"
REN "Small Town USA [%VAR6%]" "map_mp_2_black5_%VAR6%"
REN "Black's Big Battle [%VAR6%]" "map_mp_2_black6_%VAR6%"
REN "Tournament Tower [%VAR6%]" "map_mp_2_black7_%VAR6%"
REN "Tiber River Valley [%VAR6%]" "map_mp_2_black8_%VAR6%"
REN "Pipeline Problems [%VAR6%]" "map_mp_2_black9_%VAR6%"
REN "Tournament Coastline [%VAR6%]" "map_mp_2_chuck1_%VAR6%"
REN "Riverside Rumble [%VAR6%]" "map_mp_2_simon_%VAR6%"
REN "Tournament Rift [%VAR6%]" "map_mp_2_will1_%VAR6%"
REN "Unfair Advantage [%VAR6%]" "map_mp_3_black1_%VAR6%"
REN "Triple Threat [%VAR6%]" "map_mp_3_black2_%VAR6%"
REN "Downtown Dustbowl [%VAR6%]" "map_mp_4_bass_%VAR6%"
REN "The Battle for Middle Egypt [%VAR6%]" "map_mp_4_bender_%VAR6%"
REN "Crater of Carnage [%VAR6%]" "map_mp_4_black1_%VAR6%"
REN "Death Valley [%VAR6%]" "map_mp_4_black5_%VAR6%"
REN "Backwater Brawl [%VAR6%]" "map_mp_4_black6_%VAR6%"
REN "Coastline Chaos [%VAR6%]" "map_mp_4_chuck1_%VAR6%"
REN "Wrecktropolis [%VAR6%]" "map_mp_4_chuck2_%VAR6%"
REN "Redzone Rampage [%VAR6%]" "map_mp_4_rao_%VAR6%"
REN "Frontier Fracas [%VAR6%]" "map_mp_4_ssmith_01_%VAR6%"
REN "Tiberium Gardens III [%VAR6%]" "map_mp_5_black1_%VAR6%"
REN "Black's Bigger Battle [%VAR6%]" "map_mp_6_black1_%VAR6%"
REN "Six Shooter Showdown [%VAR6%]" "map_mp_6_black2_%VAR6%"
REN "Dead Six [%VAR6%]" "map_mp_6_hayes_%VAR6%"
REN "The Rocktagon [%VAR6%]" "map_mp_8_bass_%VAR6%"
REN "Bordertown Beatdown [%VAR6%]" "map_mp_8_black1_%VAR6%"
REN "Decrepit Arena [%VAR6%]" "map_mp_2_black2_redzoned_%VAR6%"
REN "Blighted Tower [%VAR6%]" "map_mp_2_black7_redzoned_%VAR6%"
REN "Gunship Gauntlet [%VAR6%]" "map_mp_2_black11_redzoned_%VAR6%"
REN "Ruined River [%VAR6%]" "map_mp_2_simon_b_%VAR6%"
REN "Cut 3player Map #1 [%VAR6%]" "EAMAP_SB01_3_%VAR6%"
REN "Cut 3player Map #2 [%VAR6%]" "EAMAP_SB02_3_%VAR6%"
REN "Cut 3player Map #3 [%VAR6%]" "EAMAP_SB03_3_%VAR6%"
REN "Cut 3player Map #4 [%VAR6%]" "EAMAP_SB04_3_%VAR6%"

REN "Seaport Smackdown [%VAR7%]" "bamap_aw01_04_%VAR7%"
REN "Grasslands Landgrab [%VAR7%]" "bamap_dc01_4_%VAR7%"
REN "Badlands [%VAR7%]" "bamap_dc02_4_%VAR7%"
REN "Desolation [%VAR7%]" "bamap_dc03_3_%VAR7%"
REN "End of the Line [%VAR7%]" "bamap_dc04_3_%VAR7%"
REN "Tournament Decision [%VAR7%]" "bamap_dc05_2_%VAR7%"
REN "Split Decision [%VAR7%]" "bamap_dc05_3_%VAR7%"
REN "Arid Remains [%VAR7%]" "bamap_dc06_4_%VAR7%"
REN "Mountains of Madness [%VAR7%]" "bamap_dc07_4_%VAR7%"
REN "Crosstown Conflict [%VAR7%]" "bamap_dc08_4_%VAR7%"
REN "Murderers Row [%VAR7%]" "bamap_dc10_4_%VAR7%"
REN "Empire City [%VAR7%]" "bamap_dc11_4_%VAR7%"
REN "Unsound Investment [%VAR7%]" "bamap_ew01_4_%VAR7%"
REN "Oasis Onslaught [%VAR7%]" "bamap_ew03_04_%VAR7%"
REN "Safety Nest [%VAR7%]" "bamap_ew05_04_%VAR7%"
REN "Shell Shocked [%VAR7%]" "bamap_ew06_04_%VAR7%"
REN "Urban Blight [%VAR7%]" "bamap_ew07_04_%VAR7%"
REN "Eastern Promises [%VAR7%]" "bamap_ew08_04_%VAR7%"
REN "Suburban Slaughterhouse [%VAR7%]" "bamap_ew09_03_%VAR7%"
REN "Tiberium Wasteland [%VAR7%]" "bamap_ew10_06_%VAR7%"
REN "Isthmus of Insanity [%VAR7%]" "bamap_ew11_05_%VAR7%"
REN "Dockside Devastation [%VAR7%]" "bamap_jf01_4_%VAR7%"
REN "Dark Waters [%VAR7%]" "bamap_jf03_6_%VAR7%"
REN "Tundra Triangle [%VAR7%]" "bamap_kk03_3_%VAR7%"
REN "Heaven and Hell [%VAR7%]" "bamap_rh01_4_%VAR7%"
REN "Missed Opportunity [%VAR7%]" "bamap_sb01_4_%VAR7%"
REN "Craters of Camden [%VAR7%]" "eamap_sb05_4_%VAR7%"
REN "Tournament Dustbowl [%VAR7%]" "map_mp_2_bass1_%VAR7%"
REN "Tournament Desert Redux [%VAR7%]" "map_mp_2_black1_%VAR7%"
REN "Deadly Sertao [%VAR7%]" "map_mp_2_black10_%VAR7%"
REN "Top Gun [%VAR7%]" "map_mp_2_black11_%VAR7%"
REN "Schlachtfeld Stuttgart [%VAR7%]" "map_mp_2_black12_%VAR7%"
REN "Tournament Arena [%VAR7%]" "map_mp_2_black2_%VAR7%"
REN "Barstow Badlands [%VAR7%]" "map_mp_2_black3_%VAR7%"
REN "Ground Zero [%VAR7%]" "map_mp_2_black4_%VAR7%"
REN "Small Town USA [%VAR7%]" "map_mp_2_black5_%VAR7%"
REN "Black's Big Battle [%VAR7%]" "map_mp_2_black6_%VAR7%"
REN "Tournament Tower [%VAR7%]" "map_mp_2_black7_%VAR7%"
REN "Tiber River Valley [%VAR7%]" "map_mp_2_black8_%VAR7%"
REN "Pipeline Problems [%VAR7%]" "map_mp_2_black9_%VAR7%"
REN "Tournament Coastline [%VAR7%]" "map_mp_2_chuck1_%VAR7%"
REN "Riverside Rumble [%VAR7%]" "map_mp_2_simon_%VAR7%"
REN "Tournament Rift [%VAR7%]" "map_mp_2_will1_%VAR7%"
REN "Unfair Advantage [%VAR7%]" "map_mp_3_black1_%VAR7%"
REN "Triple Threat [%VAR7%]" "map_mp_3_black2_%VAR7%"
REN "Downtown Dustbowl [%VAR7%]" "map_mp_4_bass_%VAR7%"
REN "The Battle for Middle Egypt [%VAR7%]" "map_mp_4_bender_%VAR7%"
REN "Crater of Carnage [%VAR7%]" "map_mp_4_black1_%VAR7%"
REN "Death Valley [%VAR7%]" "map_mp_4_black5_%VAR7%"
REN "Backwater Brawl [%VAR7%]" "map_mp_4_black6_%VAR7%"
REN "Coastline Chaos [%VAR7%]" "map_mp_4_chuck1_%VAR7%"
REN "Wrecktropolis [%VAR7%]" "map_mp_4_chuck2_%VAR7%"
REN "Redzone Rampage [%VAR7%]" "map_mp_4_rao_%VAR7%"
REN "Frontier Fracas [%VAR7%]" "map_mp_4_ssmith_01_%VAR7%"
REN "Tiberium Gardens III [%VAR7%]" "map_mp_5_black1_%VAR7%"
REN "Black's Bigger Battle [%VAR7%]" "map_mp_6_black1_%VAR7%"
REN "Six Shooter Showdown [%VAR7%]" "map_mp_6_black2_%VAR7%"
REN "Dead Six [%VAR7%]" "map_mp_6_hayes_%VAR7%"
REN "The Rocktagon [%VAR7%]" "map_mp_8_bass_%VAR7%"
REN "Bordertown Beatdown [%VAR7%]" "map_mp_8_black1_%VAR7%"
REN "Decrepit Arena [%VAR7%]" "map_mp_2_black2_redzoned_%VAR7%"
REN "Blighted Tower [%VAR7%]" "map_mp_2_black7_redzoned_%VAR7%"
REN "Gunship Gauntlet [%VAR7%]" "map_mp_2_black11_redzoned_%VAR7%"
REN "Ruined River [%VAR7%]" "map_mp_2_simon_b_%VAR7%"
REN "Cut 3player Map #1 [%VAR7%]" "EAMAP_SB01_3_%VAR7%"
REN "Cut 3player Map #2 [%VAR7%]" "EAMAP_SB02_3_%VAR7%"
REN "Cut 3player Map #3 [%VAR7%]" "EAMAP_SB03_3_%VAR7%"
REN "Cut 3player Map #4 [%VAR7%]" "EAMAP_SB04_3_%VAR7%

PAUSE