@ECHO OFF

@CD /d "%~dp0"

SET "MAP01=bamap_aw01_04"
SET "MAP02=bamap_dc01_4"
SET "MAP03=bamap_dc02_4"
SET "MAP04=bamap_dc03_3"
SET "MAP05=bamap_dc04_3"
SET "MAP06=bamap_dc05_2"
SET "MAP07=bamap_dc05_3"
SET "MAP08=bamap_dc06_4"
SET "MAP09=bamap_dc07_4"
SET "MAP10=bamap_dc08_4"
SET "MAP11=bamap_dc10_4"
SET "MAP12=bamap_dc11_4"
SET "MAP13=bamap_ew01_4"
SET "MAP14=bamap_ew03_04"
SET "MAP15=bamap_ew05_04"
SET "MAP16=bamap_ew06_04"
SET "MAP17=bamap_ew07_04"
SET "MAP18=bamap_ew08_04"
SET "MAP19=bamap_ew09_03"
SET "MAP20=bamap_ew10_06"
SET "MAP21=bamap_ew11_05"
SET "MAP22=bamap_jf01_4"
SET "MAP23=bamap_jf03_6"
SET "MAP24=bamap_kk03_3"
SET "MAP25=bamap_rh01_4"
SET "MAP26=bamap_sb01_4"
SET "MAP27=EAMAP_SB05_4"
SET "MAP28=map_mp_2_bass1"
SET "MAP29=map_mp_2_black1"
SET "MAP30=map_mp_2_black2"
SET "MAP31=map_mp_2_black3"
SET "MAP32=map_mp_2_black4"
SET "MAP33=map_mp_2_black5"
SET "MAP34=map_mp_2_black6"
SET "MAP35=map_mp_2_black7"
SET "MAP36=map_mp_2_black8"
SET "MAP37=map_mp_2_black9"
SET "MAP38=map_mp_2_black10"
SET "MAP39=map_mp_2_black11"
SET "MAP40=map_mp_2_black12"
SET "MAP41=map_mp_2_chuck1"
SET "MAP42=map_mp_2_simon"
SET "MAP43=map_mp_2_will1"
SET "MAP44=map_mp_3_black1"
SET "MAP45=map_mp_3_black2"
SET "MAP46=map_mp_4_bass"
SET "MAP47=map_mp_4_bender"
SET "MAP48=map_mp_4_black1"
SET "MAP49=map_mp_4_black5"
SET "MAP50=map_mp_4_black6"
SET "MAP51=map_mp_4_chuck1"
SET "MAP52=map_mp_4_chuck2"
SET "MAP53=map_mp_4_rao"
SET "MAP54=map_mp_4_ssmith_01"
SET "MAP55=map_mp_5_black1"
SET "MAP56=map_mp_6_black1"
SET "MAP57=map_mp_6_black2"
SET "MAP58=map_mp_6_hayes"
SET "MAP59=map_mp_8_bass"
SET "MAP60=map_mp_8_black1"
SET "MAP61=MAP_MP_2_BLACK2_redzoned"
SET "MAP62=MAP_MP_2_BLACK7_redzoned"
SET "MAP63=MAP_MP_2_BLACK11_redzoned"
SET "MAP64=MAP_MP_2_SIMON_B"
SET "MAP65=EAMAP_SB01_3"
SET "MAP66=EAMAP_SB02_3"
SET "MAP67=EAMAP_SB03_3"
SET "MAP68=EAMAP_SB04_3"

SET VAR1=INFONLY
SET VAR2=LONEWOLF
SET VAR3=NOAIR
SET VAR4=NOSW
SET VAR5=NOSW_NOAIR
SET VAR6=NOSW_NOUP
SET VAR7=TNKSONLY

SET "MAPDIR=C:\Users\Jenkins\AppData\Roaming\Command & Conquer 3 Kane's Wrath\Maps"
SET "SSR=K:\GitHub\JM-Tools\Snippets & Old Stuff\Renamers\ssr.exe"
REM "%MAPDIR%\_%VAR1%\%MAP01%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP01%_%VAR1%\map_mod.xml"

:: Usage: ssr <occurrence> <search_text> <replace_text> <input_file> [<output_file>]
:: <occurrence> - An integer specifying which occurrence to replace, use 0 for all.
:: Use '' to represent " in search and replace text.
:: Use /SSR_QUOTE/ to represent ' in search and replace text.
:: Use /SSR_NL/ to represent a new line in search and replace text.
:: Use /SSR_TAB/ to represent a tab in search and replace text.

:: "%SSR%" 0 "replacethis" "withthis" "inthisfile" "newfile"

REM DisplayName="map_mp_2_bass1_INFONLY"

"%SSR%" 0 "DisplayName=''bamap_aw01_04_%VAR1%" "DisplayName=''Seaport Smackdown [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP01%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP01%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc01_4_%VAR1%" "DisplayName=''Grasslands Landgrab [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP02%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP02%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc02_4_%VAR1%" "DisplayName=''Badlands [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP03%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP03%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc03_3_%VAR1%" "DisplayName=''Desolation [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP04%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP04%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc04_3_%VAR1%" "DisplayName=''End of the Line [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP05%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP05%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_2_%VAR1%" "DisplayName=''Tournament Decision [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP06%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP06%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_3_%VAR1%" "DisplayName=''Split Decision [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP07%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP07%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc06_4_%VAR1%" "DisplayName=''Arid Remains [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP08%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP08%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc07_4_%VAR1%" "DisplayName=''Mountains of Madness [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP09%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP09%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc08_4_%VAR1%" "DisplayName=''Crosstown Conflict [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP10%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP10%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc10_4_%VAR1%" "DisplayName=''Murderers Row [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP11%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP11%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc11_4_%VAR1%" "DisplayName=''Empire City [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP12%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP12%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew01_4_%VAR1%" "DisplayName=''Unsound Investment [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP13%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP13%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew03_04_%VAR1%" "DisplayName=''Oasis Onslaught [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP14%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP14%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew05_04_%VAR1%" "DisplayName=''Safety Nest [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP15%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP15%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew06_04_%VAR1%" "DisplayName=''Shell Shocked [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP16%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP16%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew07_04_%VAR1%" "DisplayName=''Urban Blight [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP17%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP17%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew08_04_%VAR1%" "DisplayName=''Eastern Promises [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP18%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP18%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew09_03_%VAR1%" "DisplayName=''Suburban Slaughterhouse [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP19%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP19%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew10_06_%VAR1%" "DisplayName=''Tiberium Wasteland [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP20%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP20%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew11_05_%VAR1%" "DisplayName=''Isthmus of Insanity [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP21%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP21%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf01_4_%VAR1%" "DisplayName=''Dockside Devastation [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP22%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP22%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf03_6_%VAR1%" "DisplayName=''Dark Waters [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP23%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP23%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_kk03_3_%VAR1%" "DisplayName=''Tundra Triangle [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP24%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP24%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_rh01_4_%VAR1%" "DisplayName=''Heaven and Hell [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP25%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP25%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_sb01_4_%VAR1%" "DisplayName=''Missed Opportunity [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP26%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP26%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''eamap_sb05_4_%VAR1%" "DisplayName=''Craters of Camden [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP27%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP27%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_bass1_%VAR1%" "DisplayName=''Tournament Dustbowl [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP28%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP28%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black1_%VAR1%" "DisplayName=''Tournament Desert Redux [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP29%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP29%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black10_%VAR1%" "DisplayName=''Deadly Sertao [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP30%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP30%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_%VAR1%" "DisplayName=''Top Gun [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP31%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP31%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black12_%VAR1%" "DisplayName=''Schlachtfeld Stuttgart [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP32%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP32%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_%VAR1%" "DisplayName=''Tournament Arena [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP33%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP33%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black3_%VAR1%" "DisplayName=''Barstow Badlands [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP34%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP34%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black4_%VAR1%" "DisplayName=''Ground Zero [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP35%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP35%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black5_%VAR1%" "DisplayName=''Small Town USA [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP36%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP36%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black6_%VAR1%" "DisplayName=''Black's Big Battle [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP37%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP37%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_%VAR1%" "DisplayName=''Tournament Tower [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP38%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP38%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black8_%VAR1%" "DisplayName=''Tiber River Valley [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP39%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP39%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black9_%VAR1%" "DisplayName=''Pipeline Problems [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP40%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP40%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_chuck1_%VAR1%" "DisplayName=''Tournament Coastline [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP41%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP41%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_%VAR1%" "DisplayName=''Riverside Rumble [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP42%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP42%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_will1_%VAR1%" "DisplayName=''Tournament Rift [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP43%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP43%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black1_%VAR1%" "DisplayName=''Unfair Advantage [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP44%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP44%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black2_%VAR1%" "DisplayName=''Triple Threat [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP45%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP45%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bass_%VAR1%" "DisplayName=''Downtown Dustbowl [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP46%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP46%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bender_%VAR1%" "DisplayName=''The Battle for Middle Egypt [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP47%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP47%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black1_%VAR1%" "DisplayName=''Crater of Carnage [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP48%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP48%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black5_%VAR1%" "DisplayName=''Death Valley [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP49%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP49%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black6_%VAR1%" "DisplayName=''Backwater Brawl [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP50%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP50%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck1_%VAR1%" "DisplayName=''Coastline Chaos [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP51%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP51%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck2_%VAR1%" "DisplayName=''Wrecktropolis [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP52%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP52%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_rao_%VAR1%" "DisplayName=''Redzone Rampage [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP53%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP53%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_ssmith_01_%VAR1%" "DisplayName=''Frontier Fracas [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP54%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP54%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_5_black1_%VAR1%" "DisplayName=''Tiberium Gardens III [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP55%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP55%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black1_%VAR1%" "DisplayName=''Black's Bigger Battle [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP56%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP56%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black2_%VAR1%" "DisplayName=''Six Shooter Showdown [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP57%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP57%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_hayes_%VAR1%" "DisplayName=''Dead Six [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP58%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP58%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_bass_%VAR1%" "DisplayName=''The Rocktagon [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP59%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP59%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_black1_%VAR1%" "DisplayName=''Bordertown Beatdown [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP60%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP60%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_redzoned_%VAR1%" "DisplayName=''Decrepit Arena [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP61%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP61%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_redzoned_%VAR1%" "DisplayName=''Blighted Tower [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP62%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP62%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_redzoned_%VAR1%" "DisplayName=''Gunship Gauntlet [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP63%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP63%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_b_%VAR1%" "DisplayName=''Ruined River [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP64%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP64%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB01_3_%VAR1%" "DisplayName=''Cut 3player Map #1 [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP65%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP65%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB02_3_%VAR1%" "DisplayName=''Cut 3player Map #2 [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP66%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP66%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB03_3_%VAR1%" "DisplayName=''Cut 3player Map #3 [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP67%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP67%_%VAR1%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB04_3_%VAR1%" "DisplayName=''Cut 3player Map #4 [%VAR1%]''" "%MAPDIR%\_%VAR1%\%MAP68%_%VAR1%\map.xml" "%MAPDIR%\_%VAR1%\%MAP68%_%VAR1%\map_mod.xml"

"%SSR%" 0 "DisplayName=''bamap_aw01_04_%VAR2%" "DisplayName=''Seaport Smackdown [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP01%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP01%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc01_4_%VAR2%" "DisplayName=''Grasslands Landgrab [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP02%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP02%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc02_4_%VAR2%" "DisplayName=''Badlands [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP03%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP03%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc03_3_%VAR2%" "DisplayName=''Desolation [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP04%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP04%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc04_3_%VAR2%" "DisplayName=''End of the Line [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP05%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP05%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_2_%VAR2%" "DisplayName=''Tournament Decision [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP06%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP06%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_3_%VAR2%" "DisplayName=''Split Decision [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP07%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP07%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc06_4_%VAR2%" "DisplayName=''Arid Remains [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP08%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP08%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc07_4_%VAR2%" "DisplayName=''Mountains of Madness [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP09%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP09%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc08_4_%VAR2%" "DisplayName=''Crosstown Conflict [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP10%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP10%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc10_4_%VAR2%" "DisplayName=''Murderers Row [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP11%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP11%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc11_4_%VAR2%" "DisplayName=''Empire City [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP12%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP12%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew01_4_%VAR2%" "DisplayName=''Unsound Investment [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP13%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP13%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew03_04_%VAR2%" "DisplayName=''Oasis Onslaught [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP14%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP14%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew05_04_%VAR2%" "DisplayName=''Safety Nest [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP15%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP15%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew06_04_%VAR2%" "DisplayName=''Shell Shocked [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP16%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP16%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew07_04_%VAR2%" "DisplayName=''Urban Blight [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP17%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP17%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew08_04_%VAR2%" "DisplayName=''Eastern Promises [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP18%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP18%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew09_03_%VAR2%" "DisplayName=''Suburban Slaughterhouse [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP19%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP19%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew10_06_%VAR2%" "DisplayName=''Tiberium Wasteland [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP20%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP20%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew11_05_%VAR2%" "DisplayName=''Isthmus of Insanity [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP21%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP21%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf01_4_%VAR2%" "DisplayName=''Dockside Devastation [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP22%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP22%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf03_6_%VAR2%" "DisplayName=''Dark Waters [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP23%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP23%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_kk03_3_%VAR2%" "DisplayName=''Tundra Triangle [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP24%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP24%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_rh01_4_%VAR2%" "DisplayName=''Heaven and Hell [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP25%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP25%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_sb01_4_%VAR2%" "DisplayName=''Missed Opportunity [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP26%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP26%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''eamap_sb05_4_%VAR2%" "DisplayName=''Craters of Camden [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP27%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP27%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_bass1_%VAR2%" "DisplayName=''Tournament Dustbowl [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP28%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP28%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black1_%VAR2%" "DisplayName=''Tournament Desert Redux [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP29%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP29%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black10_%VAR2%" "DisplayName=''Deadly Sertao [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP30%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP30%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_%VAR2%" "DisplayName=''Top Gun [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP31%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP31%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black12_%VAR2%" "DisplayName=''Schlachtfeld Stuttgart [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP32%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP32%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_%VAR2%" "DisplayName=''Tournament Arena [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP33%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP33%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black3_%VAR2%" "DisplayName=''Barstow Badlands [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP34%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP34%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black4_%VAR2%" "DisplayName=''Ground Zero [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP35%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP35%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black5_%VAR2%" "DisplayName=''Small Town USA [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP36%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP36%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black6_%VAR2%" "DisplayName=''Black's Big Battle [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP37%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP37%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_%VAR2%" "DisplayName=''Tournament Tower [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP38%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP38%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black8_%VAR2%" "DisplayName=''Tiber River Valley [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP39%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP39%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black9_%VAR2%" "DisplayName=''Pipeline Problems [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP40%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP40%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_chuck1_%VAR2%" "DisplayName=''Tournament Coastline [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP41%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP41%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_%VAR2%" "DisplayName=''Riverside Rumble [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP42%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP42%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_will1_%VAR2%" "DisplayName=''Tournament Rift [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP43%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP43%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black1_%VAR2%" "DisplayName=''Unfair Advantage [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP44%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP44%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black2_%VAR2%" "DisplayName=''Triple Threat [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP45%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP45%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bass_%VAR2%" "DisplayName=''Downtown Dustbowl [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP46%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP46%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bender_%VAR2%" "DisplayName=''The Battle for Middle Egypt [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP47%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP47%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black1_%VAR2%" "DisplayName=''Crater of Carnage [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP48%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP48%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black5_%VAR2%" "DisplayName=''Death Valley [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP49%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP49%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black6_%VAR2%" "DisplayName=''Backwater Brawl [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP50%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP50%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck1_%VAR2%" "DisplayName=''Coastline Chaos [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP51%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP51%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck2_%VAR2%" "DisplayName=''Wrecktropolis [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP52%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP52%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_rao_%VAR2%" "DisplayName=''Redzone Rampage [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP53%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP53%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_ssmith_01_%VAR2%" "DisplayName=''Frontier Fracas [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP54%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP54%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_5_black1_%VAR2%" "DisplayName=''Tiberium Gardens III [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP55%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP55%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black1_%VAR2%" "DisplayName=''Black's Bigger Battle [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP56%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP56%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black2_%VAR2%" "DisplayName=''Six Shooter Showdown [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP57%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP57%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_hayes_%VAR2%" "DisplayName=''Dead Six [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP58%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP58%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_bass_%VAR2%" "DisplayName=''The Rocktagon [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP59%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP59%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_black1_%VAR2%" "DisplayName=''Bordertown Beatdown [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP60%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP60%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_redzoned_%VAR2%" "DisplayName=''Decrepit Arena [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP61%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP61%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_redzoned_%VAR2%" "DisplayName=''Blighted Tower [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP62%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP62%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_redzoned_%VAR2%" "DisplayName=''Gunship Gauntlet [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP63%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP63%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_b_%VAR2%" "DisplayName=''Ruined River [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP64%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP64%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB01_3_%VAR2%" "DisplayName=''Cut 3player Map #1 [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP65%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP65%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB02_3_%VAR2%" "DisplayName=''Cut 3player Map #2 [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP66%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP66%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB03_3_%VAR2%" "DisplayName=''Cut 3player Map #3 [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP67%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP67%_%VAR2%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB04_3_%VAR2%" "DisplayName=''Cut 3player Map #4 [%VAR2%]''" "%MAPDIR%\_%VAR2%\%MAP68%_%VAR2%\map.xml" "%MAPDIR%\_%VAR2%\%MAP68%_%VAR2%\map_mod.xml"

"%SSR%" 0 "DisplayName=''bamap_aw01_04_%VAR3%" "DisplayName=''Seaport Smackdown [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP01%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP01%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc01_4_%VAR3%" "DisplayName=''Grasslands Landgrab [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP02%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP02%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc02_4_%VAR3%" "DisplayName=''Badlands [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP03%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP03%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc03_3_%VAR3%" "DisplayName=''Desolation [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP04%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP04%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc04_3_%VAR3%" "DisplayName=''End of the Line [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP05%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP05%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_2_%VAR3%" "DisplayName=''Tournament Decision [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP06%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP06%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_3_%VAR3%" "DisplayName=''Split Decision [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP07%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP07%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc06_4_%VAR3%" "DisplayName=''Arid Remains [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP08%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP08%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc07_4_%VAR3%" "DisplayName=''Mountains of Madness [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP09%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP09%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc08_4_%VAR3%" "DisplayName=''Crosstown Conflict [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP10%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP10%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc10_4_%VAR3%" "DisplayName=''Murderers Row [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP11%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP11%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc11_4_%VAR3%" "DisplayName=''Empire City [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP12%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP12%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew01_4_%VAR3%" "DisplayName=''Unsound Investment [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP13%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP13%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew03_04_%VAR3%" "DisplayName=''Oasis Onslaught [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP14%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP14%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew05_04_%VAR3%" "DisplayName=''Safety Nest [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP15%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP15%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew06_04_%VAR3%" "DisplayName=''Shell Shocked [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP16%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP16%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew07_04_%VAR3%" "DisplayName=''Urban Blight [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP17%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP17%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew08_04_%VAR3%" "DisplayName=''Eastern Promises [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP18%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP18%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew09_03_%VAR3%" "DisplayName=''Suburban Slaughterhouse [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP19%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP19%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew10_06_%VAR3%" "DisplayName=''Tiberium Wasteland [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP20%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP20%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew11_05_%VAR3%" "DisplayName=''Isthmus of Insanity [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP21%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP21%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf01_4_%VAR3%" "DisplayName=''Dockside Devastation [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP22%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP22%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf03_6_%VAR3%" "DisplayName=''Dark Waters [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP23%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP23%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_kk03_3_%VAR3%" "DisplayName=''Tundra Triangle [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP24%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP24%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_rh01_4_%VAR3%" "DisplayName=''Heaven and Hell [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP25%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP25%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_sb01_4_%VAR3%" "DisplayName=''Missed Opportunity [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP26%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP26%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''eamap_sb05_4_%VAR3%" "DisplayName=''Craters of Camden [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP27%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP27%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_bass1_%VAR3%" "DisplayName=''Tournament Dustbowl [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP28%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP28%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black1_%VAR3%" "DisplayName=''Tournament Desert Redux [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP29%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP29%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black10_%VAR3%" "DisplayName=''Deadly Sertao [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP30%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP30%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_%VAR3%" "DisplayName=''Top Gun [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP31%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP31%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black12_%VAR3%" "DisplayName=''Schlachtfeld Stuttgart [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP32%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP32%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_%VAR3%" "DisplayName=''Tournament Arena [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP33%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP33%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black3_%VAR3%" "DisplayName=''Barstow Badlands [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP34%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP34%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black4_%VAR3%" "DisplayName=''Ground Zero [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP35%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP35%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black5_%VAR3%" "DisplayName=''Small Town USA [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP36%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP36%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black6_%VAR3%" "DisplayName=''Black's Big Battle [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP37%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP37%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_%VAR3%" "DisplayName=''Tournament Tower [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP38%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP38%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black8_%VAR3%" "DisplayName=''Tiber River Valley [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP39%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP39%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black9_%VAR3%" "DisplayName=''Pipeline Problems [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP40%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP40%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_chuck1_%VAR3%" "DisplayName=''Tournament Coastline [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP41%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP41%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_%VAR3%" "DisplayName=''Riverside Rumble [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP42%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP42%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_will1_%VAR3%" "DisplayName=''Tournament Rift [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP43%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP43%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black1_%VAR3%" "DisplayName=''Unfair Advantage [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP44%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP44%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black2_%VAR3%" "DisplayName=''Triple Threat [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP45%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP45%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bass_%VAR3%" "DisplayName=''Downtown Dustbowl [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP46%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP46%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bender_%VAR3%" "DisplayName=''The Battle for Middle Egypt [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP47%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP47%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black1_%VAR3%" "DisplayName=''Crater of Carnage [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP48%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP48%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black5_%VAR3%" "DisplayName=''Death Valley [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP49%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP49%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black6_%VAR3%" "DisplayName=''Backwater Brawl [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP50%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP50%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck1_%VAR3%" "DisplayName=''Coastline Chaos [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP51%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP51%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck2_%VAR3%" "DisplayName=''Wrecktropolis [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP52%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP52%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_rao_%VAR3%" "DisplayName=''Redzone Rampage [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP53%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP53%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_ssmith_01_%VAR3%" "DisplayName=''Frontier Fracas [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP54%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP54%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_5_black1_%VAR3%" "DisplayName=''Tiberium Gardens III [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP55%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP55%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black1_%VAR3%" "DisplayName=''Black's Bigger Battle [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP56%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP56%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black2_%VAR3%" "DisplayName=''Six Shooter Showdown [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP57%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP57%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_hayes_%VAR3%" "DisplayName=''Dead Six [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP58%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP58%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_bass_%VAR3%" "DisplayName=''The Rocktagon [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP59%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP59%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_black1_%VAR3%" "DisplayName=''Bordertown Beatdown [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP60%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP60%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_redzoned_%VAR3%" "DisplayName=''Decrepit Arena [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP61%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP61%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_redzoned_%VAR3%" "DisplayName=''Blighted Tower [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP62%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP62%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_redzoned_%VAR3%" "DisplayName=''Gunship Gauntlet [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP63%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP63%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_b_%VAR3%" "DisplayName=''Ruined River [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP64%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP64%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB01_3_%VAR3%" "DisplayName=''Cut 3player Map #1 [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP65%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP65%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB02_3_%VAR3%" "DisplayName=''Cut 3player Map #2 [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP66%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP66%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB03_3_%VAR3%" "DisplayName=''Cut 3player Map #3 [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP67%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP67%_%VAR3%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB04_3_%VAR3%" "DisplayName=''Cut 3player Map #4 [%VAR3%]''" "%MAPDIR%\_%VAR3%\%MAP68%_%VAR3%\map.xml" "%MAPDIR%\_%VAR3%\%MAP68%_%VAR3%\map_mod.xml"

"%SSR%" 0 "DisplayName=''bamap_aw01_04_%VAR4%" "DisplayName=''Seaport Smackdown [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP01%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP01%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc01_4_%VAR4%" "DisplayName=''Grasslands Landgrab [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP02%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP02%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc02_4_%VAR4%" "DisplayName=''Badlands [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP03%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP03%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc03_3_%VAR4%" "DisplayName=''Desolation [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP04%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP04%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc04_3_%VAR4%" "DisplayName=''End of the Line [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP05%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP05%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_2_%VAR4%" "DisplayName=''Tournament Decision [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP06%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP06%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_3_%VAR4%" "DisplayName=''Split Decision [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP07%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP07%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc06_4_%VAR4%" "DisplayName=''Arid Remains [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP08%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP08%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc07_4_%VAR4%" "DisplayName=''Mountains of Madness [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP09%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP09%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc08_4_%VAR4%" "DisplayName=''Crosstown Conflict [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP10%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP10%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc10_4_%VAR4%" "DisplayName=''Murderers Row [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP11%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP11%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc11_4_%VAR4%" "DisplayName=''Empire City [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP12%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP12%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew01_4_%VAR4%" "DisplayName=''Unsound Investment [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP13%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP13%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew03_04_%VAR4%" "DisplayName=''Oasis Onslaught [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP14%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP14%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew05_04_%VAR4%" "DisplayName=''Safety Nest [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP15%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP15%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew06_04_%VAR4%" "DisplayName=''Shell Shocked [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP16%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP16%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew07_04_%VAR4%" "DisplayName=''Urban Blight [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP17%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP17%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew08_04_%VAR4%" "DisplayName=''Eastern Promises [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP18%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP18%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew09_03_%VAR4%" "DisplayName=''Suburban Slaughterhouse [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP19%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP19%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew10_06_%VAR4%" "DisplayName=''Tiberium Wasteland [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP20%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP20%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew11_05_%VAR4%" "DisplayName=''Isthmus of Insanity [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP21%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP21%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf01_4_%VAR4%" "DisplayName=''Dockside Devastation [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP22%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP22%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf03_6_%VAR4%" "DisplayName=''Dark Waters [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP23%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP23%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_kk03_3_%VAR4%" "DisplayName=''Tundra Triangle [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP24%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP24%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_rh01_4_%VAR4%" "DisplayName=''Heaven and Hell [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP25%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP25%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_sb01_4_%VAR4%" "DisplayName=''Missed Opportunity [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP26%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP26%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''eamap_sb05_4_%VAR4%" "DisplayName=''Craters of Camden [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP27%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP27%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_bass1_%VAR4%" "DisplayName=''Tournament Dustbowl [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP28%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP28%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black1_%VAR4%" "DisplayName=''Tournament Desert Redux [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP29%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP29%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black10_%VAR4%" "DisplayName=''Deadly Sertao [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP30%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP30%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_%VAR4%" "DisplayName=''Top Gun [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP31%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP31%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black12_%VAR4%" "DisplayName=''Schlachtfeld Stuttgart [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP32%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP32%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_%VAR4%" "DisplayName=''Tournament Arena [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP33%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP33%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black3_%VAR4%" "DisplayName=''Barstow Badlands [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP34%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP34%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black4_%VAR4%" "DisplayName=''Ground Zero [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP35%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP35%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black5_%VAR4%" "DisplayName=''Small Town USA [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP36%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP36%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black6_%VAR4%" "DisplayName=''Black's Big Battle [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP37%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP37%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_%VAR4%" "DisplayName=''Tournament Tower [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP38%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP38%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black8_%VAR4%" "DisplayName=''Tiber River Valley [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP39%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP39%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black9_%VAR4%" "DisplayName=''Pipeline Problems [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP40%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP40%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_chuck1_%VAR4%" "DisplayName=''Tournament Coastline [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP41%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP41%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_%VAR4%" "DisplayName=''Riverside Rumble [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP42%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP42%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_will1_%VAR4%" "DisplayName=''Tournament Rift [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP43%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP43%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black1_%VAR4%" "DisplayName=''Unfair Advantage [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP44%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP44%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black2_%VAR4%" "DisplayName=''Triple Threat [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP45%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP45%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bass_%VAR4%" "DisplayName=''Downtown Dustbowl [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP46%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP46%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bender_%VAR4%" "DisplayName=''The Battle for Middle Egypt [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP47%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP47%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black1_%VAR4%" "DisplayName=''Crater of Carnage [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP48%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP48%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black5_%VAR4%" "DisplayName=''Death Valley [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP49%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP49%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black6_%VAR4%" "DisplayName=''Backwater Brawl [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP50%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP50%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck1_%VAR4%" "DisplayName=''Coastline Chaos [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP51%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP51%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck2_%VAR4%" "DisplayName=''Wrecktropolis [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP52%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP52%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_rao_%VAR4%" "DisplayName=''Redzone Rampage [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP53%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP53%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_ssmith_01_%VAR4%" "DisplayName=''Frontier Fracas [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP54%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP54%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_5_black1_%VAR4%" "DisplayName=''Tiberium Gardens III [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP55%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP55%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black1_%VAR4%" "DisplayName=''Black's Bigger Battle [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP56%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP56%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black2_%VAR4%" "DisplayName=''Six Shooter Showdown [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP57%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP57%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_hayes_%VAR4%" "DisplayName=''Dead Six [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP58%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP58%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_bass_%VAR4%" "DisplayName=''The Rocktagon [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP59%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP59%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_black1_%VAR4%" "DisplayName=''Bordertown Beatdown [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP60%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP60%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_redzoned_%VAR4%" "DisplayName=''Decrepit Arena [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP61%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP61%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_redzoned_%VAR4%" "DisplayName=''Blighted Tower [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP62%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP62%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_redzoned_%VAR4%" "DisplayName=''Gunship Gauntlet [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP63%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP63%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_b_%VAR4%" "DisplayName=''Ruined River [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP64%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP64%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB01_3_%VAR4%" "DisplayName=''Cut 3player Map #1 [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP65%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP65%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB02_3_%VAR4%" "DisplayName=''Cut 3player Map #2 [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP66%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP66%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB03_3_%VAR4%" "DisplayName=''Cut 3player Map #3 [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP67%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP67%_%VAR4%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB04_3_%VAR4%" "DisplayName=''Cut 3player Map #4 [%VAR4%]''" "%MAPDIR%\_%VAR4%\%MAP68%_%VAR4%\map.xml" "%MAPDIR%\_%VAR4%\%MAP68%_%VAR4%\map_mod.xml"

"%SSR%" 0 "DisplayName=''bamap_aw01_04_%VAR5%" "DisplayName=''Seaport Smackdown [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP01%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP01%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc01_4_%VAR5%" "DisplayName=''Grasslands Landgrab [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP02%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP02%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc02_4_%VAR5%" "DisplayName=''Badlands [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP03%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP03%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc03_3_%VAR5%" "DisplayName=''Desolation [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP04%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP04%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc04_3_%VAR5%" "DisplayName=''End of the Line [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP05%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP05%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_2_%VAR5%" "DisplayName=''Tournament Decision [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP06%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP06%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_3_%VAR5%" "DisplayName=''Split Decision [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP07%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP07%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc06_4_%VAR5%" "DisplayName=''Arid Remains [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP08%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP08%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc07_4_%VAR5%" "DisplayName=''Mountains of Madness [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP09%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP09%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc08_4_%VAR5%" "DisplayName=''Crosstown Conflict [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP10%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP10%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc10_4_%VAR5%" "DisplayName=''Murderers Row [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP11%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP11%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc11_4_%VAR5%" "DisplayName=''Empire City [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP12%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP12%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew01_4_%VAR5%" "DisplayName=''Unsound Investment [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP13%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP13%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew03_04_%VAR5%" "DisplayName=''Oasis Onslaught [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP14%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP14%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew05_04_%VAR5%" "DisplayName=''Safety Nest [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP15%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP15%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew06_04_%VAR5%" "DisplayName=''Shell Shocked [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP16%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP16%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew07_04_%VAR5%" "DisplayName=''Urban Blight [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP17%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP17%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew08_04_%VAR5%" "DisplayName=''Eastern Promises [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP18%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP18%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew09_03_%VAR5%" "DisplayName=''Suburban Slaughterhouse [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP19%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP19%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew10_06_%VAR5%" "DisplayName=''Tiberium Wasteland [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP20%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP20%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew11_05_%VAR5%" "DisplayName=''Isthmus of Insanity [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP21%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP21%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf01_4_%VAR5%" "DisplayName=''Dockside Devastation [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP22%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP22%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf03_6_%VAR5%" "DisplayName=''Dark Waters [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP23%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP23%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_kk03_3_%VAR5%" "DisplayName=''Tundra Triangle [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP24%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP24%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_rh01_4_%VAR5%" "DisplayName=''Heaven and Hell [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP25%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP25%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_sb01_4_%VAR5%" "DisplayName=''Missed Opportunity [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP26%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP26%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''eamap_sb05_4_%VAR5%" "DisplayName=''Craters of Camden [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP27%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP27%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_bass1_%VAR5%" "DisplayName=''Tournament Dustbowl [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP28%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP28%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black1_%VAR5%" "DisplayName=''Tournament Desert Redux [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP29%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP29%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black10_%VAR5%" "DisplayName=''Deadly Sertao [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP30%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP30%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_%VAR5%" "DisplayName=''Top Gun [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP31%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP31%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black12_%VAR5%" "DisplayName=''Schlachtfeld Stuttgart [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP32%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP32%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_%VAR5%" "DisplayName=''Tournament Arena [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP33%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP33%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black3_%VAR5%" "DisplayName=''Barstow Badlands [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP34%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP34%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black4_%VAR5%" "DisplayName=''Ground Zero [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP35%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP35%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black5_%VAR5%" "DisplayName=''Small Town USA [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP36%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP36%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black6_%VAR5%" "DisplayName=''Black's Big Battle [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP37%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP37%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_%VAR5%" "DisplayName=''Tournament Tower [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP38%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP38%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black8_%VAR5%" "DisplayName=''Tiber River Valley [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP39%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP39%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black9_%VAR5%" "DisplayName=''Pipeline Problems [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP40%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP40%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_chuck1_%VAR5%" "DisplayName=''Tournament Coastline [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP41%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP41%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_%VAR5%" "DisplayName=''Riverside Rumble [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP42%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP42%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_will1_%VAR5%" "DisplayName=''Tournament Rift [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP43%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP43%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black1_%VAR5%" "DisplayName=''Unfair Advantage [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP44%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP44%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black2_%VAR5%" "DisplayName=''Triple Threat [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP45%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP45%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bass_%VAR5%" "DisplayName=''Downtown Dustbowl [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP46%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP46%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bender_%VAR5%" "DisplayName=''The Battle for Middle Egypt [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP47%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP47%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black1_%VAR5%" "DisplayName=''Crater of Carnage [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP48%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP48%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black5_%VAR5%" "DisplayName=''Death Valley [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP49%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP49%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black6_%VAR5%" "DisplayName=''Backwater Brawl [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP50%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP50%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck1_%VAR5%" "DisplayName=''Coastline Chaos [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP51%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP51%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck2_%VAR5%" "DisplayName=''Wrecktropolis [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP52%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP52%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_rao_%VAR5%" "DisplayName=''Redzone Rampage [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP53%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP53%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_ssmith_01_%VAR5%" "DisplayName=''Frontier Fracas [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP54%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP54%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_5_black1_%VAR5%" "DisplayName=''Tiberium Gardens III [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP55%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP55%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black1_%VAR5%" "DisplayName=''Black's Bigger Battle [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP56%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP56%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black2_%VAR5%" "DisplayName=''Six Shooter Showdown [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP57%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP57%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_hayes_%VAR5%" "DisplayName=''Dead Six [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP58%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP58%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_bass_%VAR5%" "DisplayName=''The Rocktagon [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP59%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP59%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_black1_%VAR5%" "DisplayName=''Bordertown Beatdown [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP60%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP60%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_redzoned_%VAR5%" "DisplayName=''Decrepit Arena [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP61%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP61%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_redzoned_%VAR5%" "DisplayName=''Blighted Tower [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP62%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP62%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_redzoned_%VAR5%" "DisplayName=''Gunship Gauntlet [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP63%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP63%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_b_%VAR5%" "DisplayName=''Ruined River [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP64%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP64%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB01_3_%VAR5%" "DisplayName=''Cut 3player Map #1 [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP65%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP65%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB02_3_%VAR5%" "DisplayName=''Cut 3player Map #2 [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP66%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP66%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB03_3_%VAR5%" "DisplayName=''Cut 3player Map #3 [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP67%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP67%_%VAR5%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB04_3_%VAR5%" "DisplayName=''Cut 3player Map #4 [%VAR5%]''" "%MAPDIR%\_%VAR5%\%MAP68%_%VAR5%\map.xml" "%MAPDIR%\_%VAR5%\%MAP68%_%VAR5%\map_mod.xml"

"%SSR%" 0 "DisplayName=''bamap_aw01_04_%VAR6%" "DisplayName=''Seaport Smackdown [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP01%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP01%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc01_4_%VAR6%" "DisplayName=''Grasslands Landgrab [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP02%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP02%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc02_4_%VAR6%" "DisplayName=''Badlands [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP03%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP03%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc03_3_%VAR6%" "DisplayName=''Desolation [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP04%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP04%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc04_3_%VAR6%" "DisplayName=''End of the Line [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP05%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP05%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_2_%VAR6%" "DisplayName=''Tournament Decision [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP06%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP06%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_3_%VAR6%" "DisplayName=''Split Decision [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP07%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP07%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc06_4_%VAR6%" "DisplayName=''Arid Remains [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP08%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP08%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc07_4_%VAR6%" "DisplayName=''Mountains of Madness [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP09%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP09%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc08_4_%VAR6%" "DisplayName=''Crosstown Conflict [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP10%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP10%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc10_4_%VAR6%" "DisplayName=''Murderers Row [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP11%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP11%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc11_4_%VAR6%" "DisplayName=''Empire City [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP12%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP12%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew01_4_%VAR6%" "DisplayName=''Unsound Investment [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP13%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP13%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew03_04_%VAR6%" "DisplayName=''Oasis Onslaught [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP14%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP14%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew05_04_%VAR6%" "DisplayName=''Safety Nest [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP15%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP15%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew06_04_%VAR6%" "DisplayName=''Shell Shocked [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP16%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP16%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew07_04_%VAR6%" "DisplayName=''Urban Blight [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP17%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP17%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew08_04_%VAR6%" "DisplayName=''Eastern Promises [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP18%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP18%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew09_03_%VAR6%" "DisplayName=''Suburban Slaughterhouse [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP19%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP19%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew10_06_%VAR6%" "DisplayName=''Tiberium Wasteland [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP20%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP20%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew11_05_%VAR6%" "DisplayName=''Isthmus of Insanity [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP21%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP21%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf01_4_%VAR6%" "DisplayName=''Dockside Devastation [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP22%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP22%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf03_6_%VAR6%" "DisplayName=''Dark Waters [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP23%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP23%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_kk03_3_%VAR6%" "DisplayName=''Tundra Triangle [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP24%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP24%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_rh01_4_%VAR6%" "DisplayName=''Heaven and Hell [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP25%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP25%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_sb01_4_%VAR6%" "DisplayName=''Missed Opportunity [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP26%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP26%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''eamap_sb05_4_%VAR6%" "DisplayName=''Craters of Camden [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP27%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP27%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_bass1_%VAR6%" "DisplayName=''Tournament Dustbowl [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP28%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP28%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black1_%VAR6%" "DisplayName=''Tournament Desert Redux [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP29%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP29%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black10_%VAR6%" "DisplayName=''Deadly Sertao [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP30%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP30%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_%VAR6%" "DisplayName=''Top Gun [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP31%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP31%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black12_%VAR6%" "DisplayName=''Schlachtfeld Stuttgart [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP32%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP32%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_%VAR6%" "DisplayName=''Tournament Arena [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP33%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP33%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black3_%VAR6%" "DisplayName=''Barstow Badlands [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP34%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP34%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black4_%VAR6%" "DisplayName=''Ground Zero [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP35%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP35%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black5_%VAR6%" "DisplayName=''Small Town USA [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP36%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP36%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black6_%VAR6%" "DisplayName=''Black's Big Battle [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP37%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP37%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_%VAR6%" "DisplayName=''Tournament Tower [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP38%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP38%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black8_%VAR6%" "DisplayName=''Tiber River Valley [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP39%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP39%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black9_%VAR6%" "DisplayName=''Pipeline Problems [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP40%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP40%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_chuck1_%VAR6%" "DisplayName=''Tournament Coastline [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP41%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP41%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_%VAR6%" "DisplayName=''Riverside Rumble [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP42%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP42%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_will1_%VAR6%" "DisplayName=''Tournament Rift [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP43%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP43%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black1_%VAR6%" "DisplayName=''Unfair Advantage [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP44%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP44%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black2_%VAR6%" "DisplayName=''Triple Threat [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP45%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP45%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bass_%VAR6%" "DisplayName=''Downtown Dustbowl [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP46%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP46%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bender_%VAR6%" "DisplayName=''The Battle for Middle Egypt [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP47%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP47%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black1_%VAR6%" "DisplayName=''Crater of Carnage [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP48%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP48%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black5_%VAR6%" "DisplayName=''Death Valley [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP49%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP49%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black6_%VAR6%" "DisplayName=''Backwater Brawl [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP50%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP50%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck1_%VAR6%" "DisplayName=''Coastline Chaos [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP51%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP51%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck2_%VAR6%" "DisplayName=''Wrecktropolis [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP52%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP52%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_rao_%VAR6%" "DisplayName=''Redzone Rampage [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP53%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP53%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_ssmith_01_%VAR6%" "DisplayName=''Frontier Fracas [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP54%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP54%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_5_black1_%VAR6%" "DisplayName=''Tiberium Gardens III [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP55%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP55%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black1_%VAR6%" "DisplayName=''Black's Bigger Battle [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP56%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP56%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black2_%VAR6%" "DisplayName=''Six Shooter Showdown [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP57%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP57%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_hayes_%VAR6%" "DisplayName=''Dead Six [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP58%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP58%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_bass_%VAR6%" "DisplayName=''The Rocktagon [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP59%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP59%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_black1_%VAR6%" "DisplayName=''Bordertown Beatdown [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP60%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP60%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_redzoned_%VAR6%" "DisplayName=''Decrepit Arena [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP61%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP61%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_redzoned_%VAR6%" "DisplayName=''Blighted Tower [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP62%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP62%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_redzoned_%VAR6%" "DisplayName=''Gunship Gauntlet [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP63%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP63%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_b_%VAR6%" "DisplayName=''Ruined River [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP64%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP64%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB01_3_%VAR6%" "DisplayName=''Cut 3player Map #1 [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP65%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP65%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB02_3_%VAR6%" "DisplayName=''Cut 3player Map #2 [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP66%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP66%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB03_3_%VAR6%" "DisplayName=''Cut 3player Map #3 [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP67%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP67%_%VAR6%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB04_3_%VAR6%" "DisplayName=''Cut 3player Map #4 [%VAR6%]''" "%MAPDIR%\_%VAR6%\%MAP68%_%VAR6%\map.xml" "%MAPDIR%\_%VAR6%\%MAP68%_%VAR6%\map_mod.xml"

"%SSR%" 0 "DisplayName=''bamap_aw01_04_%VAR7%" "DisplayName=''Seaport Smackdown [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP01%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP01%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc01_4_%VAR7%" "DisplayName=''Grasslands Landgrab [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP02%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP02%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc02_4_%VAR7%" "DisplayName=''Badlands [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP03%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP03%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc03_3_%VAR7%" "DisplayName=''Desolation [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP04%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP04%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc04_3_%VAR7%" "DisplayName=''End of the Line [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP05%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP05%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_2_%VAR7%" "DisplayName=''Tournament Decision [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP06%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP06%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc05_3_%VAR7%" "DisplayName=''Split Decision [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP07%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP07%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc06_4_%VAR7%" "DisplayName=''Arid Remains [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP08%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP08%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc07_4_%VAR7%" "DisplayName=''Mountains of Madness [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP09%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP09%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc08_4_%VAR7%" "DisplayName=''Crosstown Conflict [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP10%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP10%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc10_4_%VAR7%" "DisplayName=''Murderers Row [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP11%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP11%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_dc11_4_%VAR7%" "DisplayName=''Empire City [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP12%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP12%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew01_4_%VAR7%" "DisplayName=''Unsound Investment [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP13%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP13%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew03_04_%VAR7%" "DisplayName=''Oasis Onslaught [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP14%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP14%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew05_04_%VAR7%" "DisplayName=''Safety Nest [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP15%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP15%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew06_04_%VAR7%" "DisplayName=''Shell Shocked [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP16%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP16%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew07_04_%VAR7%" "DisplayName=''Urban Blight [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP17%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP17%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew08_04_%VAR7%" "DisplayName=''Eastern Promises [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP18%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP18%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew09_03_%VAR7%" "DisplayName=''Suburban Slaughterhouse [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP19%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP19%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew10_06_%VAR7%" "DisplayName=''Tiberium Wasteland [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP20%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP20%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_ew11_05_%VAR7%" "DisplayName=''Isthmus of Insanity [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP21%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP21%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf01_4_%VAR7%" "DisplayName=''Dockside Devastation [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP22%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP22%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_jf03_6_%VAR7%" "DisplayName=''Dark Waters [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP23%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP23%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_kk03_3_%VAR7%" "DisplayName=''Tundra Triangle [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP24%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP24%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_rh01_4_%VAR7%" "DisplayName=''Heaven and Hell [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP25%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP25%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''bamap_sb01_4_%VAR7%" "DisplayName=''Missed Opportunity [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP26%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP26%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''eamap_sb05_4_%VAR7%" "DisplayName=''Craters of Camden [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP27%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP27%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_bass1_%VAR7%" "DisplayName=''Tournament Dustbowl [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP28%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP28%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black1_%VAR7%" "DisplayName=''Tournament Desert Redux [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP29%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP29%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black10_%VAR7%" "DisplayName=''Deadly Sertao [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP30%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP30%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_%VAR7%" "DisplayName=''Top Gun [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP31%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP31%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black12_%VAR7%" "DisplayName=''Schlachtfeld Stuttgart [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP32%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP32%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_%VAR7%" "DisplayName=''Tournament Arena [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP33%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP33%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black3_%VAR7%" "DisplayName=''Barstow Badlands [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP34%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP34%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black4_%VAR7%" "DisplayName=''Ground Zero [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP35%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP35%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black5_%VAR7%" "DisplayName=''Small Town USA [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP36%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP36%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black6_%VAR7%" "DisplayName=''Black's Big Battle [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP37%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP37%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_%VAR7%" "DisplayName=''Tournament Tower [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP38%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP38%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black8_%VAR7%" "DisplayName=''Tiber River Valley [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP39%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP39%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black9_%VAR7%" "DisplayName=''Pipeline Problems [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP40%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP40%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_chuck1_%VAR7%" "DisplayName=''Tournament Coastline [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP41%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP41%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_%VAR7%" "DisplayName=''Riverside Rumble [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP42%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP42%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_will1_%VAR7%" "DisplayName=''Tournament Rift [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP43%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP43%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black1_%VAR7%" "DisplayName=''Unfair Advantage [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP44%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP44%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_3_black2_%VAR7%" "DisplayName=''Triple Threat [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP45%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP45%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bass_%VAR7%" "DisplayName=''Downtown Dustbowl [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP46%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP46%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_bender_%VAR7%" "DisplayName=''The Battle for Middle Egypt [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP47%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP47%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black1_%VAR7%" "DisplayName=''Crater of Carnage [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP48%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP48%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black5_%VAR7%" "DisplayName=''Death Valley [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP49%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP49%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_black6_%VAR7%" "DisplayName=''Backwater Brawl [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP50%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP50%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck1_%VAR7%" "DisplayName=''Coastline Chaos [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP51%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP51%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_chuck2_%VAR7%" "DisplayName=''Wrecktropolis [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP52%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP52%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_rao_%VAR7%" "DisplayName=''Redzone Rampage [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP53%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP53%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_4_ssmith_01_%VAR7%" "DisplayName=''Frontier Fracas [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP54%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP54%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_5_black1_%VAR7%" "DisplayName=''Tiberium Gardens III [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP55%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP55%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black1_%VAR7%" "DisplayName=''Black's Bigger Battle [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP56%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP56%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_black2_%VAR7%" "DisplayName=''Six Shooter Showdown [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP57%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP57%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_6_hayes_%VAR7%" "DisplayName=''Dead Six [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP58%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP58%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_bass_%VAR7%" "DisplayName=''The Rocktagon [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP59%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP59%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_8_black1_%VAR7%" "DisplayName=''Bordertown Beatdown [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP60%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP60%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black2_redzoned_%VAR7%" "DisplayName=''Decrepit Arena [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP61%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP61%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black7_redzoned_%VAR7%" "DisplayName=''Blighted Tower [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP62%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP62%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_black11_redzoned_%VAR7%" "DisplayName=''Gunship Gauntlet [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP63%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP63%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''map_mp_2_simon_b_%VAR7%" "DisplayName=''Ruined River [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP64%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP64%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB01_3_%VAR7%" "DisplayName=''Cut 3player Map #1 [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP65%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP65%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB02_3_%VAR7%" "DisplayName=''Cut 3player Map #2 [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP66%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP66%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB03_3_%VAR7%" "DisplayName=''Cut 3player Map #3 [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP67%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP67%_%VAR7%\map_mod.xml"
"%SSR%" 0 "DisplayName=''EAMAP_SB04_3_%VAR7%" "DisplayName=''Cut 3player Map #4 [%VAR7%]''" "%MAPDIR%\_%VAR7%\%MAP68%_%VAR7%\map.xml" "%MAPDIR%\_%VAR7%\%MAP68%_%VAR7%\map_mod.xml"

PAUSE