@ECHO OFF

@CD /d "%~dp0"

SET "MAP01=bamap_aw01_04"
SET "MAP02=bamap_dc01_4"
SET "MAP03=bamap_dc02_4"
SET "MAP04=bamap_dc03_3"
SET "MAP05=bamap_dc04_3"
SET "MAP06=bamap_dc05_2"
SET "MAP07=bamap_dc05_3"
SET "MAP08=bamap_dc06_4"
SET "MAP09=bamap_dc07_4"
SET "MAP10=bamap_dc08_4"
SET "MAP11=bamap_dc10_4"
SET "MAP12=bamap_dc11_4"
SET "MAP13=bamap_ew01_4"
SET "MAP14=bamap_ew03_04"
SET "MAP15=bamap_ew05_04"
SET "MAP16=bamap_ew06_04"
SET "MAP17=bamap_ew07_04"
SET "MAP18=bamap_ew08_04"
SET "MAP19=bamap_ew09_03"
SET "MAP20=bamap_ew10_06"
SET "MAP21=bamap_ew11_05"
SET "MAP22=bamap_jf01_4"
SET "MAP23=bamap_jf03_6"
SET "MAP24=bamap_kk03_3"
SET "MAP25=bamap_rh01_4"
SET "MAP26=bamap_sb01_4"
SET "MAP27=EAMAP_SB05_4"
SET "MAP28=map_mp_2_bass1"
SET "MAP29=map_mp_2_black1"
SET "MAP30=map_mp_2_black2"
SET "MAP31=map_mp_2_black3"
SET "MAP32=map_mp_2_black4"
SET "MAP33=map_mp_2_black5"
SET "MAP34=map_mp_2_black6"
SET "MAP35=map_mp_2_black7"
SET "MAP36=map_mp_2_black8"
SET "MAP37=map_mp_2_black9"
SET "MAP38=map_mp_2_black10"
SET "MAP39=map_mp_2_black11"
SET "MAP40=map_mp_2_black12"
SET "MAP41=map_mp_2_chuck1"
SET "MAP42=map_mp_2_simon"
SET "MAP43=map_mp_2_will1"
SET "MAP44=map_mp_3_black1"
SET "MAP45=map_mp_3_black2"
SET "MAP46=map_mp_4_bass"
SET "MAP47=map_mp_4_bender"
SET "MAP48=map_mp_4_black1"
SET "MAP49=map_mp_4_black5"
SET "MAP50=map_mp_4_black6"
SET "MAP51=map_mp_4_chuck1"
SET "MAP52=map_mp_4_chuck2"
SET "MAP53=map_mp_4_rao"
SET "MAP54=map_mp_4_ssmith_01"
SET "MAP55=map_mp_5_black1"
SET "MAP56=map_mp_6_black1"
SET "MAP57=map_mp_6_black2"
SET "MAP58=map_mp_6_hayes"
SET "MAP59=map_mp_8_bass"
SET "MAP60=map_mp_8_black1"
SET "MAP61=MAP_MP_2_BLACK2_redzoned"
SET "MAP62=MAP_MP_2_BLACK7_redzoned"
SET "MAP63=MAP_MP_2_BLACK11_redzoned"
SET "MAP64=MAP_MP_2_SIMON_B"
SET "MAP65=EAMAP_SB01_3"
SET "MAP66=EAMAP_SB02_3"
SET "MAP67=EAMAP_SB03_3"
SET "MAP68=EAMAP_SB04_3"

SET "MAPN01=Seaport Smackdown"
SET "MAPN02=Grasslands Landgrab"
SET "MAPN03=Badlands"
SET "MAPN04=Desolation"
SET "MAPN05=End of the Line"
SET "MAPN06=Tournament Decision"
SET "MAPN07=Split Decision"
SET "MAPN08=Arid Remains"
SET "MAPN09=Mountains of Madness"
SET "MAPN10=Crosstown Conflict"
SET "MAPN11=Murderers Row"
SET "MAPN12=Empire City"
SET "MAPN13=Unsound Investment"
SET "MAPN14=Oasis Onslaught"
SET "MAPN15=Safety Nest"
SET "MAPN16=Shell Shocked"
SET "MAPN17=Urban Blight"
SET "MAPN18=Eastern Promises"
SET "MAPN19=Suburban Slaughterhouse"
SET "MAPN20=Tiberium Wasteland"
SET "MAPN21=Isthmus of Insanity"
SET "MAPN22=Dockside Devastation"
SET "MAPN23=Dark Waters"
SET "MAPN24=Tundra Triangle"
SET "MAPN25=Heaven and Hell"
SET "MAPN26=Missed Opportunity"
SET "MAPN27=Craters of Camden"
SET "MAPN28=Tournament Dustbowl"
SET "MAPN29=Tournament Desert Redux"
SET "MAPN30=Deadly Sertao"
SET "MAPN31=Top Gun"
SET "MAPN32=Schlachtfeld Stuttgart"
SET "MAPN33=Tournament Arena"
SET "MAPN34=Barstow Badlands"
SET "MAPN35=Ground Zero"
SET "MAPN36=Small Town USA"
SET "MAPN37=Black's Big Battle"
SET "MAPN38=Tournament Tower"
SET "MAPN39=Tiber River Valley"
SET "MAPN40=Pipeline Problems"
SET "MAPN41=Tournament Coastline"
SET "MAPN42=Riverside Rumble"
SET "MAPN43=Tournament Rift"
SET "MAPN44=Unfair Advantage"
SET "MAPN45=Triple Threat"
SET "MAPN46=Downtown Dustbowl"
SET "MAPN47=The Battle for Middle Egypt"
SET "MAPN48=Crater of Carnage"
SET "MAPN49=Death Valley"
SET "MAPN50=Backwater Brawl"
SET "MAPN51=Coastline Chaos"
SET "MAPN52=Wrecktropolis"
SET "MAPN53=Redzone Rampage"
SET "MAPN54=Frontier Fracas"
SET "MAPN55=Tiberium Gardens III"
SET "MAPN56=Black's Bigger Battle"
SET "MAPN57=Six Shooter Showdown"
SET "MAPN58=Dead Six"
SET "MAPN59=The Rocktagon"
SET "MAPN60=Bordertown Beatdown"
SET "MAPN61=Decrepit Arena"
SET "MAPN62=Blighted Tower"
SET "MAPN63=Gunship Gauntlet"
SET "MAPN64=Ruined River"
SET "MAPN65=Cut 3player Map #1"
SET "MAPN66=Cut 3player Map #2"
SET "MAPN67=Cut 3player Map #3"
SET "MAPN68=Cut 3player Map #4"

SET VAR1=INFONLY
SET VAR2=LONEWOLF
SET VAR3=NOAIR
SET VAR4=NOSW
SET VAR5=NOSW_NOAIR
SET VAR6=NOSW_NOUP
SET VAR7=TNKSONLY

SET "MAPDIR=C:\Users\Jenkins\AppData\Roaming\Command & Conquer 3 Kane's Wrath\Maps"
SET "SSR=K:\GitHub\JM-Tools\Snippets & Old Stuff\Renamers\ssr.exe"
REM "%MAPDIR%\%MAPN01% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN01% (%VAR1%)\map_mod.xml"

:: Usage: ssr <occurrence> <search_text> <replace_text> <input_file> (<output_file>]
:: <occurrence> - An integer specifying which occurrence to replace, use 0 for all.
:: Use '' to represent " in search and replace text.
:: Use /SSR_QUOTE/ to represent ' in search and replace text.
:: Use /SSR_NL/ to represent a new line in search and replace text.
:: Use /SSR_TAB/ to represent a tab in search and replace text.

:: "%SSR%" 0 "replacethis" "withthis" "inthisfile" "newfile"

REM DisplayName="map_mp_2_bass1_INFONLY"

"%SSR%" 0 "Description=''Map:bamap_aw01_04_%VAR1%" "Description=''Map:Seaport Smackdown (%VAR1%)" "%MAPDIR%\%MAPN01% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN01% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc01_4_%VAR1%" "Description=''Map:Grasslands Landgrab (%VAR1%)" "%MAPDIR%\%MAPN02% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN02% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc02_4_%VAR1%" "Description=''Map:Badlands (%VAR1%)" "%MAPDIR%\%MAPN03% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN03% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc03_3_%VAR1%" "Description=''Map:Desolation (%VAR1%)" "%MAPDIR%\%MAPN04% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN04% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc04_3_%VAR1%" "Description=''Map:End of the Line (%VAR1%)" "%MAPDIR%\%MAPN05% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN05% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_2_%VAR1%" "Description=''Map:Tournament Decision (%VAR1%)" "%MAPDIR%\%MAPN06% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN06% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_3_%VAR1%" "Description=''Map:Split Decision (%VAR1%)" "%MAPDIR%\%MAPN07% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN07% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc06_4_%VAR1%" "Description=''Map:Arid Remains (%VAR1%)" "%MAPDIR%\%MAPN08% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN08% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc07_4_%VAR1%" "Description=''Map:Mountains of Madness (%VAR1%)" "%MAPDIR%\%MAPN09% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN09% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc08_4_%VAR1%" "Description=''Map:Crosstown Conflict (%VAR1%)" "%MAPDIR%\%MAPN10% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN10% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc10_4_%VAR1%" "Description=''Map:Murderers Row (%VAR1%)" "%MAPDIR%\%MAPN11% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN11% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc11_4_%VAR1%" "Description=''Map:Empire City (%VAR1%)" "%MAPDIR%\%MAPN12% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN12% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew01_4_%VAR1%" "Description=''Map:Unsound Investment (%VAR1%)" "%MAPDIR%\%MAPN13% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN13% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew03_04_%VAR1%" "Description=''Map:Oasis Onslaught (%VAR1%)" "%MAPDIR%\%MAPN14% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN14% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew05_04_%VAR1%" "Description=''Map:Safety Nest (%VAR1%)" "%MAPDIR%\%MAPN15% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN15% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew06_04_%VAR1%" "Description=''Map:Shell Shocked (%VAR1%)" "%MAPDIR%\%MAPN16% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN16% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew07_04_%VAR1%" "Description=''Map:Urban Blight (%VAR1%)" "%MAPDIR%\%MAPN17% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN17% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew08_04_%VAR1%" "Description=''Map:Eastern Promises (%VAR1%)" "%MAPDIR%\%MAPN18% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN18% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew09_03_%VAR1%" "Description=''Map:Suburban Slaughterhouse (%VAR1%)" "%MAPDIR%\%MAPN19% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN19% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew10_06_%VAR1%" "Description=''Map:Tiberium Wasteland (%VAR1%)" "%MAPDIR%\%MAPN20% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN20% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew11_05_%VAR1%" "Description=''Map:Isthmus of Insanity (%VAR1%)" "%MAPDIR%\%MAPN21% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN21% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf01_4_%VAR1%" "Description=''Map:Dockside Devastation (%VAR1%)" "%MAPDIR%\%MAPN22% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN22% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf03_6_%VAR1%" "Description=''Map:Dark Waters (%VAR1%)" "%MAPDIR%\%MAPN23% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN23% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_kk03_3_%VAR1%" "Description=''Map:Tundra Triangle (%VAR1%)" "%MAPDIR%\%MAPN24% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN24% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_rh01_4_%VAR1%" "Description=''Map:Heaven and Hell (%VAR1%)" "%MAPDIR%\%MAPN25% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN25% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_sb01_4_%VAR1%" "Description=''Map:Missed Opportunity (%VAR1%)" "%MAPDIR%\%MAPN26% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN26% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:eamap_sb05_4_%VAR1%" "Description=''Map:Craters of Camden (%VAR1%)" "%MAPDIR%\%MAPN27% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN27% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_bass1_%VAR1%" "Description=''Map:Tournament Dustbowl (%VAR1%)" "%MAPDIR%\%MAPN28% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN28% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black1_%VAR1%" "Description=''Map:Tournament Desert Redux (%VAR1%)" "%MAPDIR%\%MAPN29% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN29% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black10_%VAR1%" "Description=''Map:Deadly Sertao (%VAR1%)" "%MAPDIR%\%MAPN30% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN30% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_%VAR1%" "Description=''Map:Top Gun (%VAR1%)" "%MAPDIR%\%MAPN31% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN31% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black12_%VAR1%" "Description=''Map:Schlachtfeld Stuttgart (%VAR1%)" "%MAPDIR%\%MAPN32% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN32% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_%VAR1%" "Description=''Map:Tournament Arena (%VAR1%)" "%MAPDIR%\%MAPN33% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN33% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black3_%VAR1%" "Description=''Map:Barstow Badlands (%VAR1%)" "%MAPDIR%\%MAPN34% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN34% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black4_%VAR1%" "Description=''Map:Ground Zero (%VAR1%)" "%MAPDIR%\%MAPN35% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN35% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black5_%VAR1%" "Description=''Map:Small Town USA (%VAR1%)" "%MAPDIR%\%MAPN36% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN36% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black6_%VAR1%" "Description=''Map:Black's Big Battle (%VAR1%)" "%MAPDIR%\%MAPN37% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN37% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_%VAR1%" "Description=''Map:Tournament Tower (%VAR1%)" "%MAPDIR%\%MAPN38% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN38% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black8_%VAR1%" "Description=''Map:Tiber River Valley (%VAR1%)" "%MAPDIR%\%MAPN39% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN39% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black9_%VAR1%" "Description=''Map:Pipeline Problems (%VAR1%)" "%MAPDIR%\%MAPN40% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN40% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_chuck1_%VAR1%" "Description=''Map:Tournament Coastline (%VAR1%)" "%MAPDIR%\%MAPN41% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN41% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_%VAR1%" "Description=''Map:Riverside Rumble (%VAR1%)" "%MAPDIR%\%MAPN42% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN42% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_will1_%VAR1%" "Description=''Map:Tournament Rift (%VAR1%)" "%MAPDIR%\%MAPN43% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN43% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black1_%VAR1%" "Description=''Map:Unfair Advantage (%VAR1%)" "%MAPDIR%\%MAPN44% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN44% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black2_%VAR1%" "Description=''Map:Triple Threat (%VAR1%)" "%MAPDIR%\%MAPN45% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN45% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bass_%VAR1%" "Description=''Map:Downtown Dustbowl (%VAR1%)" "%MAPDIR%\%MAPN46% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN46% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bender_%VAR1%" "Description=''Map:The Battle for Middle Egypt (%VAR1%)" "%MAPDIR%\%MAPN47% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN47% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black1_%VAR1%" "Description=''Map:Crater of Carnage (%VAR1%)" "%MAPDIR%\%MAPN48% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN48% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black5_%VAR1%" "Description=''Map:Death Valley (%VAR1%)" "%MAPDIR%\%MAPN49% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN49% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black6_%VAR1%" "Description=''Map:Backwater Brawl (%VAR1%)" "%MAPDIR%\%MAPN50% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN50% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck1_%VAR1%" "Description=''Map:Coastline Chaos (%VAR1%)" "%MAPDIR%\%MAPN51% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN51% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck2_%VAR1%" "Description=''Map:Wrecktropolis (%VAR1%)" "%MAPDIR%\%MAPN52% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN52% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_rao_%VAR1%" "Description=''Map:Redzone Rampage (%VAR1%)" "%MAPDIR%\%MAPN53% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN53% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_ssmith_01_%VAR1%" "Description=''Map:Frontier Fracas (%VAR1%)" "%MAPDIR%\%MAPN54% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN54% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_5_black1_%VAR1%" "Description=''Map:Tiberium Gardens III (%VAR1%)" "%MAPDIR%\%MAPN55% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN55% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black1_%VAR1%" "Description=''Map:Black's Bigger Battle (%VAR1%)" "%MAPDIR%\%MAPN56% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN56% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black2_%VAR1%" "Description=''Map:Six Shooter Showdown (%VAR1%)" "%MAPDIR%\%MAPN57% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN57% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_hayes_%VAR1%" "Description=''Map:Dead Six (%VAR1%)" "%MAPDIR%\%MAPN58% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN58% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_bass_%VAR1%" "Description=''Map:The Rocktagon (%VAR1%)" "%MAPDIR%\%MAPN59% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN59% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_black1_%VAR1%" "Description=''Map:Bordertown Beatdown (%VAR1%)" "%MAPDIR%\%MAPN60% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN60% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_redzoned_%VAR1%" "Description=''Map:Decrepit Arena (%VAR1%)" "%MAPDIR%\%MAPN61% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN61% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_redzoned_%VAR1%" "Description=''Map:Blighted Tower (%VAR1%)" "%MAPDIR%\%MAPN62% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN62% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_redzoned_%VAR1%" "Description=''Map:Gunship Gauntlet (%VAR1%)" "%MAPDIR%\%MAPN63% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN63% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_b_%VAR1%" "Description=''Map:Ruined River (%VAR1%)" "%MAPDIR%\%MAPN64% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN64% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB01_3_%VAR1%" "Description=''Map:Cut 3player Map #1 (%VAR1%)" "%MAPDIR%\%MAPN65% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN65% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB02_3_%VAR1%" "Description=''Map:Cut 3player Map #2 (%VAR1%)" "%MAPDIR%\%MAPN66% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN66% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB03_3_%VAR1%" "Description=''Map:Cut 3player Map #3 (%VAR1%)" "%MAPDIR%\%MAPN67% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN67% (%VAR1%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB04_3_%VAR1%" "Description=''Map:Cut 3player Map #4 (%VAR1%)" "%MAPDIR%\%MAPN68% (%VAR1%)\map.xml" "%MAPDIR%\%MAPN68% (%VAR1%)\map_mod.xml"

"%SSR%" 0 "Description=''Map:bamap_aw01_04_%VAR2%" "Description=''Map:Seaport Smackdown (%VAR2%)" "%MAPDIR%\%MAPN01% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN01% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc01_4_%VAR2%" "Description=''Map:Grasslands Landgrab (%VAR2%)" "%MAPDIR%\%MAPN02% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN02% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc02_4_%VAR2%" "Description=''Map:Badlands (%VAR2%)" "%MAPDIR%\%MAPN03% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN03% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc03_3_%VAR2%" "Description=''Map:Desolation (%VAR2%)" "%MAPDIR%\%MAPN04% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN04% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc04_3_%VAR2%" "Description=''Map:End of the Line (%VAR2%)" "%MAPDIR%\%MAPN05% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN05% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_2_%VAR2%" "Description=''Map:Tournament Decision (%VAR2%)" "%MAPDIR%\%MAPN06% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN06% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_3_%VAR2%" "Description=''Map:Split Decision (%VAR2%)" "%MAPDIR%\%MAPN07% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN07% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc06_4_%VAR2%" "Description=''Map:Arid Remains (%VAR2%)" "%MAPDIR%\%MAPN08% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN08% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc07_4_%VAR2%" "Description=''Map:Mountains of Madness (%VAR2%)" "%MAPDIR%\%MAPN09% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN09% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc08_4_%VAR2%" "Description=''Map:Crosstown Conflict (%VAR2%)" "%MAPDIR%\%MAPN10% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN10% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc10_4_%VAR2%" "Description=''Map:Murderers Row (%VAR2%)" "%MAPDIR%\%MAPN11% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN11% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc11_4_%VAR2%" "Description=''Map:Empire City (%VAR2%)" "%MAPDIR%\%MAPN12% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN12% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew01_4_%VAR2%" "Description=''Map:Unsound Investment (%VAR2%)" "%MAPDIR%\%MAPN13% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN13% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew03_04_%VAR2%" "Description=''Map:Oasis Onslaught (%VAR2%)" "%MAPDIR%\%MAPN14% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN14% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew05_04_%VAR2%" "Description=''Map:Safety Nest (%VAR2%)" "%MAPDIR%\%MAPN15% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN15% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew06_04_%VAR2%" "Description=''Map:Shell Shocked (%VAR2%)" "%MAPDIR%\%MAPN16% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN16% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew07_04_%VAR2%" "Description=''Map:Urban Blight (%VAR2%)" "%MAPDIR%\%MAPN17% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN17% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew08_04_%VAR2%" "Description=''Map:Eastern Promises (%VAR2%)" "%MAPDIR%\%MAPN18% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN18% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew09_03_%VAR2%" "Description=''Map:Suburban Slaughterhouse (%VAR2%)" "%MAPDIR%\%MAPN19% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN19% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew10_06_%VAR2%" "Description=''Map:Tiberium Wasteland (%VAR2%)" "%MAPDIR%\%MAPN20% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN20% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew11_05_%VAR2%" "Description=''Map:Isthmus of Insanity (%VAR2%)" "%MAPDIR%\%MAPN21% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN21% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf01_4_%VAR2%" "Description=''Map:Dockside Devastation (%VAR2%)" "%MAPDIR%\%MAPN22% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN22% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf03_6_%VAR2%" "Description=''Map:Dark Waters (%VAR2%)" "%MAPDIR%\%MAPN23% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN23% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_kk03_3_%VAR2%" "Description=''Map:Tundra Triangle (%VAR2%)" "%MAPDIR%\%MAPN24% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN24% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_rh01_4_%VAR2%" "Description=''Map:Heaven and Hell (%VAR2%)" "%MAPDIR%\%MAPN25% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN25% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_sb01_4_%VAR2%" "Description=''Map:Missed Opportunity (%VAR2%)" "%MAPDIR%\%MAPN26% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN26% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:eamap_sb05_4_%VAR2%" "Description=''Map:Craters of Camden (%VAR2%)" "%MAPDIR%\%MAPN27% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN27% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_bass1_%VAR2%" "Description=''Map:Tournament Dustbowl (%VAR2%)" "%MAPDIR%\%MAPN28% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN28% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black1_%VAR2%" "Description=''Map:Tournament Desert Redux (%VAR2%)" "%MAPDIR%\%MAPN29% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN29% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black10_%VAR2%" "Description=''Map:Deadly Sertao (%VAR2%)" "%MAPDIR%\%MAPN30% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN30% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_%VAR2%" "Description=''Map:Top Gun (%VAR2%)" "%MAPDIR%\%MAPN31% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN31% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black12_%VAR2%" "Description=''Map:Schlachtfeld Stuttgart (%VAR2%)" "%MAPDIR%\%MAPN32% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN32% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_%VAR2%" "Description=''Map:Tournament Arena (%VAR2%)" "%MAPDIR%\%MAPN33% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN33% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black3_%VAR2%" "Description=''Map:Barstow Badlands (%VAR2%)" "%MAPDIR%\%MAPN34% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN34% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black4_%VAR2%" "Description=''Map:Ground Zero (%VAR2%)" "%MAPDIR%\%MAPN35% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN35% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black5_%VAR2%" "Description=''Map:Small Town USA (%VAR2%)" "%MAPDIR%\%MAPN36% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN36% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black6_%VAR2%" "Description=''Map:Black's Big Battle (%VAR2%)" "%MAPDIR%\%MAPN37% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN37% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_%VAR2%" "Description=''Map:Tournament Tower (%VAR2%)" "%MAPDIR%\%MAPN38% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN38% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black8_%VAR2%" "Description=''Map:Tiber River Valley (%VAR2%)" "%MAPDIR%\%MAPN39% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN39% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black9_%VAR2%" "Description=''Map:Pipeline Problems (%VAR2%)" "%MAPDIR%\%MAPN40% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN40% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_chuck1_%VAR2%" "Description=''Map:Tournament Coastline (%VAR2%)" "%MAPDIR%\%MAPN41% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN41% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_%VAR2%" "Description=''Map:Riverside Rumble (%VAR2%)" "%MAPDIR%\%MAPN42% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN42% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_will1_%VAR2%" "Description=''Map:Tournament Rift (%VAR2%)" "%MAPDIR%\%MAPN43% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN43% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black1_%VAR2%" "Description=''Map:Unfair Advantage (%VAR2%)" "%MAPDIR%\%MAPN44% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN44% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black2_%VAR2%" "Description=''Map:Triple Threat (%VAR2%)" "%MAPDIR%\%MAPN45% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN45% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bass_%VAR2%" "Description=''Map:Downtown Dustbowl (%VAR2%)" "%MAPDIR%\%MAPN46% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN46% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bender_%VAR2%" "Description=''Map:The Battle for Middle Egypt (%VAR2%)" "%MAPDIR%\%MAPN47% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN47% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black1_%VAR2%" "Description=''Map:Crater of Carnage (%VAR2%)" "%MAPDIR%\%MAPN48% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN48% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black5_%VAR2%" "Description=''Map:Death Valley (%VAR2%)" "%MAPDIR%\%MAPN49% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN49% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black6_%VAR2%" "Description=''Map:Backwater Brawl (%VAR2%)" "%MAPDIR%\%MAPN50% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN50% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck1_%VAR2%" "Description=''Map:Coastline Chaos (%VAR2%)" "%MAPDIR%\%MAPN51% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN51% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck2_%VAR2%" "Description=''Map:Wrecktropolis (%VAR2%)" "%MAPDIR%\%MAPN52% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN52% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_rao_%VAR2%" "Description=''Map:Redzone Rampage (%VAR2%)" "%MAPDIR%\%MAPN53% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN53% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_ssmith_01_%VAR2%" "Description=''Map:Frontier Fracas (%VAR2%)" "%MAPDIR%\%MAPN54% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN54% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_5_black1_%VAR2%" "Description=''Map:Tiberium Gardens III (%VAR2%)" "%MAPDIR%\%MAPN55% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN55% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black1_%VAR2%" "Description=''Map:Black's Bigger Battle (%VAR2%)" "%MAPDIR%\%MAPN56% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN56% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black2_%VAR2%" "Description=''Map:Six Shooter Showdown (%VAR2%)" "%MAPDIR%\%MAPN57% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN57% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_hayes_%VAR2%" "Description=''Map:Dead Six (%VAR2%)" "%MAPDIR%\%MAPN58% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN58% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_bass_%VAR2%" "Description=''Map:The Rocktagon (%VAR2%)" "%MAPDIR%\%MAPN59% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN59% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_black1_%VAR2%" "Description=''Map:Bordertown Beatdown (%VAR2%)" "%MAPDIR%\%MAPN60% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN60% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_redzoned_%VAR2%" "Description=''Map:Decrepit Arena (%VAR2%)" "%MAPDIR%\%MAPN61% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN61% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_redzoned_%VAR2%" "Description=''Map:Blighted Tower (%VAR2%)" "%MAPDIR%\%MAPN62% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN62% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_redzoned_%VAR2%" "Description=''Map:Gunship Gauntlet (%VAR2%)" "%MAPDIR%\%MAPN63% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN63% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_b_%VAR2%" "Description=''Map:Ruined River (%VAR2%)" "%MAPDIR%\%MAPN64% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN64% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB01_3_%VAR2%" "Description=''Map:Cut 3player Map #1 (%VAR2%)" "%MAPDIR%\%MAPN65% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN65% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB02_3_%VAR2%" "Description=''Map:Cut 3player Map #2 (%VAR2%)" "%MAPDIR%\%MAPN66% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN66% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB03_3_%VAR2%" "Description=''Map:Cut 3player Map #3 (%VAR2%)" "%MAPDIR%\%MAPN67% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN67% (%VAR2%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB04_3_%VAR2%" "Description=''Map:Cut 3player Map #4 (%VAR2%)" "%MAPDIR%\%MAPN68% (%VAR2%)\map.xml" "%MAPDIR%\%MAPN68% (%VAR2%)\map_mod.xml"

"%SSR%" 0 "Description=''Map:bamap_aw01_04_%VAR3%" "Description=''Map:Seaport Smackdown (%VAR3%)" "%MAPDIR%\%MAPN01% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN01% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc01_4_%VAR3%" "Description=''Map:Grasslands Landgrab (%VAR3%)" "%MAPDIR%\%MAPN02% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN02% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc02_4_%VAR3%" "Description=''Map:Badlands (%VAR3%)" "%MAPDIR%\%MAPN03% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN03% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc03_3_%VAR3%" "Description=''Map:Desolation (%VAR3%)" "%MAPDIR%\%MAPN04% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN04% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc04_3_%VAR3%" "Description=''Map:End of the Line (%VAR3%)" "%MAPDIR%\%MAPN05% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN05% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_2_%VAR3%" "Description=''Map:Tournament Decision (%VAR3%)" "%MAPDIR%\%MAPN06% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN06% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_3_%VAR3%" "Description=''Map:Split Decision (%VAR3%)" "%MAPDIR%\%MAPN07% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN07% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc06_4_%VAR3%" "Description=''Map:Arid Remains (%VAR3%)" "%MAPDIR%\%MAPN08% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN08% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc07_4_%VAR3%" "Description=''Map:Mountains of Madness (%VAR3%)" "%MAPDIR%\%MAPN09% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN09% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc08_4_%VAR3%" "Description=''Map:Crosstown Conflict (%VAR3%)" "%MAPDIR%\%MAPN10% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN10% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc10_4_%VAR3%" "Description=''Map:Murderers Row (%VAR3%)" "%MAPDIR%\%MAPN11% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN11% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc11_4_%VAR3%" "Description=''Map:Empire City (%VAR3%)" "%MAPDIR%\%MAPN12% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN12% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew01_4_%VAR3%" "Description=''Map:Unsound Investment (%VAR3%)" "%MAPDIR%\%MAPN13% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN13% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew03_04_%VAR3%" "Description=''Map:Oasis Onslaught (%VAR3%)" "%MAPDIR%\%MAPN14% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN14% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew05_04_%VAR3%" "Description=''Map:Safety Nest (%VAR3%)" "%MAPDIR%\%MAPN15% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN15% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew06_04_%VAR3%" "Description=''Map:Shell Shocked (%VAR3%)" "%MAPDIR%\%MAPN16% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN16% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew07_04_%VAR3%" "Description=''Map:Urban Blight (%VAR3%)" "%MAPDIR%\%MAPN17% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN17% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew08_04_%VAR3%" "Description=''Map:Eastern Promises (%VAR3%)" "%MAPDIR%\%MAPN18% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN18% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew09_03_%VAR3%" "Description=''Map:Suburban Slaughterhouse (%VAR3%)" "%MAPDIR%\%MAPN19% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN19% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew10_06_%VAR3%" "Description=''Map:Tiberium Wasteland (%VAR3%)" "%MAPDIR%\%MAPN20% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN20% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew11_05_%VAR3%" "Description=''Map:Isthmus of Insanity (%VAR3%)" "%MAPDIR%\%MAPN21% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN21% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf01_4_%VAR3%" "Description=''Map:Dockside Devastation (%VAR3%)" "%MAPDIR%\%MAPN22% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN22% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf03_6_%VAR3%" "Description=''Map:Dark Waters (%VAR3%)" "%MAPDIR%\%MAPN23% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN23% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_kk03_3_%VAR3%" "Description=''Map:Tundra Triangle (%VAR3%)" "%MAPDIR%\%MAPN24% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN24% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_rh01_4_%VAR3%" "Description=''Map:Heaven and Hell (%VAR3%)" "%MAPDIR%\%MAPN25% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN25% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_sb01_4_%VAR3%" "Description=''Map:Missed Opportunity (%VAR3%)" "%MAPDIR%\%MAPN26% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN26% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:eamap_sb05_4_%VAR3%" "Description=''Map:Craters of Camden (%VAR3%)" "%MAPDIR%\%MAPN27% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN27% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_bass1_%VAR3%" "Description=''Map:Tournament Dustbowl (%VAR3%)" "%MAPDIR%\%MAPN28% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN28% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black1_%VAR3%" "Description=''Map:Tournament Desert Redux (%VAR3%)" "%MAPDIR%\%MAPN29% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN29% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black10_%VAR3%" "Description=''Map:Deadly Sertao (%VAR3%)" "%MAPDIR%\%MAPN30% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN30% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_%VAR3%" "Description=''Map:Top Gun (%VAR3%)" "%MAPDIR%\%MAPN31% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN31% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black12_%VAR3%" "Description=''Map:Schlachtfeld Stuttgart (%VAR3%)" "%MAPDIR%\%MAPN32% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN32% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_%VAR3%" "Description=''Map:Tournament Arena (%VAR3%)" "%MAPDIR%\%MAPN33% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN33% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black3_%VAR3%" "Description=''Map:Barstow Badlands (%VAR3%)" "%MAPDIR%\%MAPN34% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN34% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black4_%VAR3%" "Description=''Map:Ground Zero (%VAR3%)" "%MAPDIR%\%MAPN35% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN35% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black5_%VAR3%" "Description=''Map:Small Town USA (%VAR3%)" "%MAPDIR%\%MAPN36% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN36% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black6_%VAR3%" "Description=''Map:Black's Big Battle (%VAR3%)" "%MAPDIR%\%MAPN37% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN37% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_%VAR3%" "Description=''Map:Tournament Tower (%VAR3%)" "%MAPDIR%\%MAPN38% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN38% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black8_%VAR3%" "Description=''Map:Tiber River Valley (%VAR3%)" "%MAPDIR%\%MAPN39% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN39% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black9_%VAR3%" "Description=''Map:Pipeline Problems (%VAR3%)" "%MAPDIR%\%MAPN40% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN40% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_chuck1_%VAR3%" "Description=''Map:Tournament Coastline (%VAR3%)" "%MAPDIR%\%MAPN41% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN41% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_%VAR3%" "Description=''Map:Riverside Rumble (%VAR3%)" "%MAPDIR%\%MAPN42% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN42% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_will1_%VAR3%" "Description=''Map:Tournament Rift (%VAR3%)" "%MAPDIR%\%MAPN43% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN43% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black1_%VAR3%" "Description=''Map:Unfair Advantage (%VAR3%)" "%MAPDIR%\%MAPN44% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN44% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black2_%VAR3%" "Description=''Map:Triple Threat (%VAR3%)" "%MAPDIR%\%MAPN45% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN45% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bass_%VAR3%" "Description=''Map:Downtown Dustbowl (%VAR3%)" "%MAPDIR%\%MAPN46% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN46% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bender_%VAR3%" "Description=''Map:The Battle for Middle Egypt (%VAR3%)" "%MAPDIR%\%MAPN47% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN47% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black1_%VAR3%" "Description=''Map:Crater of Carnage (%VAR3%)" "%MAPDIR%\%MAPN48% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN48% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black5_%VAR3%" "Description=''Map:Death Valley (%VAR3%)" "%MAPDIR%\%MAPN49% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN49% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black6_%VAR3%" "Description=''Map:Backwater Brawl (%VAR3%)" "%MAPDIR%\%MAPN50% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN50% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck1_%VAR3%" "Description=''Map:Coastline Chaos (%VAR3%)" "%MAPDIR%\%MAPN51% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN51% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck2_%VAR3%" "Description=''Map:Wrecktropolis (%VAR3%)" "%MAPDIR%\%MAPN52% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN52% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_rao_%VAR3%" "Description=''Map:Redzone Rampage (%VAR3%)" "%MAPDIR%\%MAPN53% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN53% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_ssmith_01_%VAR3%" "Description=''Map:Frontier Fracas (%VAR3%)" "%MAPDIR%\%MAPN54% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN54% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_5_black1_%VAR3%" "Description=''Map:Tiberium Gardens III (%VAR3%)" "%MAPDIR%\%MAPN55% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN55% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black1_%VAR3%" "Description=''Map:Black's Bigger Battle (%VAR3%)" "%MAPDIR%\%MAPN56% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN56% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black2_%VAR3%" "Description=''Map:Six Shooter Showdown (%VAR3%)" "%MAPDIR%\%MAPN57% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN57% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_hayes_%VAR3%" "Description=''Map:Dead Six (%VAR3%)" "%MAPDIR%\%MAPN58% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN58% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_bass_%VAR3%" "Description=''Map:The Rocktagon (%VAR3%)" "%MAPDIR%\%MAPN59% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN59% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_black1_%VAR3%" "Description=''Map:Bordertown Beatdown (%VAR3%)" "%MAPDIR%\%MAPN60% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN60% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_redzoned_%VAR3%" "Description=''Map:Decrepit Arena (%VAR3%)" "%MAPDIR%\%MAPN61% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN61% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_redzoned_%VAR3%" "Description=''Map:Blighted Tower (%VAR3%)" "%MAPDIR%\%MAPN62% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN62% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_redzoned_%VAR3%" "Description=''Map:Gunship Gauntlet (%VAR3%)" "%MAPDIR%\%MAPN63% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN63% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_b_%VAR3%" "Description=''Map:Ruined River (%VAR3%)" "%MAPDIR%\%MAPN64% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN64% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB01_3_%VAR3%" "Description=''Map:Cut 3player Map #1 (%VAR3%)" "%MAPDIR%\%MAPN65% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN65% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB02_3_%VAR3%" "Description=''Map:Cut 3player Map #2 (%VAR3%)" "%MAPDIR%\%MAPN66% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN66% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB03_3_%VAR3%" "Description=''Map:Cut 3player Map #3 (%VAR3%)" "%MAPDIR%\%MAPN67% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN67% (%VAR3%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB04_3_%VAR3%" "Description=''Map:Cut 3player Map #4 (%VAR3%)" "%MAPDIR%\%MAPN68% (%VAR3%)\map.xml" "%MAPDIR%\%MAPN68% (%VAR3%)\map_mod.xml"

"%SSR%" 0 "Description=''Map:bamap_aw01_04_%VAR4%" "Description=''Map:Seaport Smackdown (%VAR4%)" "%MAPDIR%\%MAPN01% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN01% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc01_4_%VAR4%" "Description=''Map:Grasslands Landgrab (%VAR4%)" "%MAPDIR%\%MAPN02% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN02% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc02_4_%VAR4%" "Description=''Map:Badlands (%VAR4%)" "%MAPDIR%\%MAPN03% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN03% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc03_3_%VAR4%" "Description=''Map:Desolation (%VAR4%)" "%MAPDIR%\%MAPN04% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN04% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc04_3_%VAR4%" "Description=''Map:End of the Line (%VAR4%)" "%MAPDIR%\%MAPN05% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN05% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_2_%VAR4%" "Description=''Map:Tournament Decision (%VAR4%)" "%MAPDIR%\%MAPN06% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN06% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_3_%VAR4%" "Description=''Map:Split Decision (%VAR4%)" "%MAPDIR%\%MAPN07% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN07% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc06_4_%VAR4%" "Description=''Map:Arid Remains (%VAR4%)" "%MAPDIR%\%MAPN08% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN08% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc07_4_%VAR4%" "Description=''Map:Mountains of Madness (%VAR4%)" "%MAPDIR%\%MAPN09% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN09% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc08_4_%VAR4%" "Description=''Map:Crosstown Conflict (%VAR4%)" "%MAPDIR%\%MAPN10% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN10% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc10_4_%VAR4%" "Description=''Map:Murderers Row (%VAR4%)" "%MAPDIR%\%MAPN11% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN11% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc11_4_%VAR4%" "Description=''Map:Empire City (%VAR4%)" "%MAPDIR%\%MAPN12% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN12% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew01_4_%VAR4%" "Description=''Map:Unsound Investment (%VAR4%)" "%MAPDIR%\%MAPN13% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN13% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew03_04_%VAR4%" "Description=''Map:Oasis Onslaught (%VAR4%)" "%MAPDIR%\%MAPN14% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN14% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew05_04_%VAR4%" "Description=''Map:Safety Nest (%VAR4%)" "%MAPDIR%\%MAPN15% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN15% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew06_04_%VAR4%" "Description=''Map:Shell Shocked (%VAR4%)" "%MAPDIR%\%MAPN16% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN16% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew07_04_%VAR4%" "Description=''Map:Urban Blight (%VAR4%)" "%MAPDIR%\%MAPN17% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN17% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew08_04_%VAR4%" "Description=''Map:Eastern Promises (%VAR4%)" "%MAPDIR%\%MAPN18% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN18% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew09_03_%VAR4%" "Description=''Map:Suburban Slaughterhouse (%VAR4%)" "%MAPDIR%\%MAPN19% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN19% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew10_06_%VAR4%" "Description=''Map:Tiberium Wasteland (%VAR4%)" "%MAPDIR%\%MAPN20% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN20% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew11_05_%VAR4%" "Description=''Map:Isthmus of Insanity (%VAR4%)" "%MAPDIR%\%MAPN21% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN21% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf01_4_%VAR4%" "Description=''Map:Dockside Devastation (%VAR4%)" "%MAPDIR%\%MAPN22% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN22% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf03_6_%VAR4%" "Description=''Map:Dark Waters (%VAR4%)" "%MAPDIR%\%MAPN23% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN23% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_kk03_3_%VAR4%" "Description=''Map:Tundra Triangle (%VAR4%)" "%MAPDIR%\%MAPN24% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN24% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_rh01_4_%VAR4%" "Description=''Map:Heaven and Hell (%VAR4%)" "%MAPDIR%\%MAPN25% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN25% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_sb01_4_%VAR4%" "Description=''Map:Missed Opportunity (%VAR4%)" "%MAPDIR%\%MAPN26% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN26% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:eamap_sb05_4_%VAR4%" "Description=''Map:Craters of Camden (%VAR4%)" "%MAPDIR%\%MAPN27% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN27% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_bass1_%VAR4%" "Description=''Map:Tournament Dustbowl (%VAR4%)" "%MAPDIR%\%MAPN28% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN28% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black1_%VAR4%" "Description=''Map:Tournament Desert Redux (%VAR4%)" "%MAPDIR%\%MAPN29% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN29% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black10_%VAR4%" "Description=''Map:Deadly Sertao (%VAR4%)" "%MAPDIR%\%MAPN30% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN30% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_%VAR4%" "Description=''Map:Top Gun (%VAR4%)" "%MAPDIR%\%MAPN31% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN31% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black12_%VAR4%" "Description=''Map:Schlachtfeld Stuttgart (%VAR4%)" "%MAPDIR%\%MAPN32% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN32% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_%VAR4%" "Description=''Map:Tournament Arena (%VAR4%)" "%MAPDIR%\%MAPN33% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN33% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black3_%VAR4%" "Description=''Map:Barstow Badlands (%VAR4%)" "%MAPDIR%\%MAPN34% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN34% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black4_%VAR4%" "Description=''Map:Ground Zero (%VAR4%)" "%MAPDIR%\%MAPN35% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN35% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black5_%VAR4%" "Description=''Map:Small Town USA (%VAR4%)" "%MAPDIR%\%MAPN36% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN36% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black6_%VAR4%" "Description=''Map:Black's Big Battle (%VAR4%)" "%MAPDIR%\%MAPN37% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN37% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_%VAR4%" "Description=''Map:Tournament Tower (%VAR4%)" "%MAPDIR%\%MAPN38% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN38% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black8_%VAR4%" "Description=''Map:Tiber River Valley (%VAR4%)" "%MAPDIR%\%MAPN39% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN39% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black9_%VAR4%" "Description=''Map:Pipeline Problems (%VAR4%)" "%MAPDIR%\%MAPN40% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN40% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_chuck1_%VAR4%" "Description=''Map:Tournament Coastline (%VAR4%)" "%MAPDIR%\%MAPN41% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN41% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_%VAR4%" "Description=''Map:Riverside Rumble (%VAR4%)" "%MAPDIR%\%MAPN42% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN42% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_will1_%VAR4%" "Description=''Map:Tournament Rift (%VAR4%)" "%MAPDIR%\%MAPN43% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN43% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black1_%VAR4%" "Description=''Map:Unfair Advantage (%VAR4%)" "%MAPDIR%\%MAPN44% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN44% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black2_%VAR4%" "Description=''Map:Triple Threat (%VAR4%)" "%MAPDIR%\%MAPN45% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN45% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bass_%VAR4%" "Description=''Map:Downtown Dustbowl (%VAR4%)" "%MAPDIR%\%MAPN46% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN46% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bender_%VAR4%" "Description=''Map:The Battle for Middle Egypt (%VAR4%)" "%MAPDIR%\%MAPN47% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN47% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black1_%VAR4%" "Description=''Map:Crater of Carnage (%VAR4%)" "%MAPDIR%\%MAPN48% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN48% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black5_%VAR4%" "Description=''Map:Death Valley (%VAR4%)" "%MAPDIR%\%MAPN49% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN49% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black6_%VAR4%" "Description=''Map:Backwater Brawl (%VAR4%)" "%MAPDIR%\%MAPN50% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN50% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck1_%VAR4%" "Description=''Map:Coastline Chaos (%VAR4%)" "%MAPDIR%\%MAPN51% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN51% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck2_%VAR4%" "Description=''Map:Wrecktropolis (%VAR4%)" "%MAPDIR%\%MAPN52% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN52% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_rao_%VAR4%" "Description=''Map:Redzone Rampage (%VAR4%)" "%MAPDIR%\%MAPN53% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN53% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_ssmith_01_%VAR4%" "Description=''Map:Frontier Fracas (%VAR4%)" "%MAPDIR%\%MAPN54% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN54% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_5_black1_%VAR4%" "Description=''Map:Tiberium Gardens III (%VAR4%)" "%MAPDIR%\%MAPN55% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN55% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black1_%VAR4%" "Description=''Map:Black's Bigger Battle (%VAR4%)" "%MAPDIR%\%MAPN56% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN56% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black2_%VAR4%" "Description=''Map:Six Shooter Showdown (%VAR4%)" "%MAPDIR%\%MAPN57% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN57% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_hayes_%VAR4%" "Description=''Map:Dead Six (%VAR4%)" "%MAPDIR%\%MAPN58% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN58% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_bass_%VAR4%" "Description=''Map:The Rocktagon (%VAR4%)" "%MAPDIR%\%MAPN59% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN59% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_black1_%VAR4%" "Description=''Map:Bordertown Beatdown (%VAR4%)" "%MAPDIR%\%MAPN60% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN60% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_redzoned_%VAR4%" "Description=''Map:Decrepit Arena (%VAR4%)" "%MAPDIR%\%MAPN61% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN61% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_redzoned_%VAR4%" "Description=''Map:Blighted Tower (%VAR4%)" "%MAPDIR%\%MAPN62% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN62% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_redzoned_%VAR4%" "Description=''Map:Gunship Gauntlet (%VAR4%)" "%MAPDIR%\%MAPN63% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN63% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_b_%VAR4%" "Description=''Map:Ruined River (%VAR4%)" "%MAPDIR%\%MAPN64% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN64% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB01_3_%VAR4%" "Description=''Map:Cut 3player Map #1 (%VAR4%)" "%MAPDIR%\%MAPN65% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN65% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB02_3_%VAR4%" "Description=''Map:Cut 3player Map #2 (%VAR4%)" "%MAPDIR%\%MAPN66% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN66% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB03_3_%VAR4%" "Description=''Map:Cut 3player Map #3 (%VAR4%)" "%MAPDIR%\%MAPN67% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN67% (%VAR4%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB04_3_%VAR4%" "Description=''Map:Cut 3player Map #4 (%VAR4%)" "%MAPDIR%\%MAPN68% (%VAR4%)\map.xml" "%MAPDIR%\%MAPN68% (%VAR4%)\map_mod.xml"

"%SSR%" 0 "Description=''Map:bamap_aw01_04_%VAR5%" "Description=''Map:Seaport Smackdown (%VAR5%)" "%MAPDIR%\%MAPN01% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN01% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc01_4_%VAR5%" "Description=''Map:Grasslands Landgrab (%VAR5%)" "%MAPDIR%\%MAPN02% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN02% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc02_4_%VAR5%" "Description=''Map:Badlands (%VAR5%)" "%MAPDIR%\%MAPN03% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN03% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc03_3_%VAR5%" "Description=''Map:Desolation (%VAR5%)" "%MAPDIR%\%MAPN04% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN04% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc04_3_%VAR5%" "Description=''Map:End of the Line (%VAR5%)" "%MAPDIR%\%MAPN05% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN05% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_2_%VAR5%" "Description=''Map:Tournament Decision (%VAR5%)" "%MAPDIR%\%MAPN06% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN06% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_3_%VAR5%" "Description=''Map:Split Decision (%VAR5%)" "%MAPDIR%\%MAPN07% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN07% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc06_4_%VAR5%" "Description=''Map:Arid Remains (%VAR5%)" "%MAPDIR%\%MAPN08% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN08% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc07_4_%VAR5%" "Description=''Map:Mountains of Madness (%VAR5%)" "%MAPDIR%\%MAPN09% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN09% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc08_4_%VAR5%" "Description=''Map:Crosstown Conflict (%VAR5%)" "%MAPDIR%\%MAPN10% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN10% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc10_4_%VAR5%" "Description=''Map:Murderers Row (%VAR5%)" "%MAPDIR%\%MAPN11% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN11% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc11_4_%VAR5%" "Description=''Map:Empire City (%VAR5%)" "%MAPDIR%\%MAPN12% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN12% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew01_4_%VAR5%" "Description=''Map:Unsound Investment (%VAR5%)" "%MAPDIR%\%MAPN13% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN13% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew03_04_%VAR5%" "Description=''Map:Oasis Onslaught (%VAR5%)" "%MAPDIR%\%MAPN14% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN14% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew05_04_%VAR5%" "Description=''Map:Safety Nest (%VAR5%)" "%MAPDIR%\%MAPN15% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN15% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew06_04_%VAR5%" "Description=''Map:Shell Shocked (%VAR5%)" "%MAPDIR%\%MAPN16% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN16% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew07_04_%VAR5%" "Description=''Map:Urban Blight (%VAR5%)" "%MAPDIR%\%MAPN17% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN17% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew08_04_%VAR5%" "Description=''Map:Eastern Promises (%VAR5%)" "%MAPDIR%\%MAPN18% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN18% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew09_03_%VAR5%" "Description=''Map:Suburban Slaughterhouse (%VAR5%)" "%MAPDIR%\%MAPN19% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN19% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew10_06_%VAR5%" "Description=''Map:Tiberium Wasteland (%VAR5%)" "%MAPDIR%\%MAPN20% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN20% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew11_05_%VAR5%" "Description=''Map:Isthmus of Insanity (%VAR5%)" "%MAPDIR%\%MAPN21% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN21% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf01_4_%VAR5%" "Description=''Map:Dockside Devastation (%VAR5%)" "%MAPDIR%\%MAPN22% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN22% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf03_6_%VAR5%" "Description=''Map:Dark Waters (%VAR5%)" "%MAPDIR%\%MAPN23% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN23% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_kk03_3_%VAR5%" "Description=''Map:Tundra Triangle (%VAR5%)" "%MAPDIR%\%MAPN24% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN24% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_rh01_4_%VAR5%" "Description=''Map:Heaven and Hell (%VAR5%)" "%MAPDIR%\%MAPN25% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN25% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_sb01_4_%VAR5%" "Description=''Map:Missed Opportunity (%VAR5%)" "%MAPDIR%\%MAPN26% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN26% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:eamap_sb05_4_%VAR5%" "Description=''Map:Craters of Camden (%VAR5%)" "%MAPDIR%\%MAPN27% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN27% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_bass1_%VAR5%" "Description=''Map:Tournament Dustbowl (%VAR5%)" "%MAPDIR%\%MAPN28% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN28% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black1_%VAR5%" "Description=''Map:Tournament Desert Redux (%VAR5%)" "%MAPDIR%\%MAPN29% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN29% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black10_%VAR5%" "Description=''Map:Deadly Sertao (%VAR5%)" "%MAPDIR%\%MAPN30% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN30% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_%VAR5%" "Description=''Map:Top Gun (%VAR5%)" "%MAPDIR%\%MAPN31% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN31% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black12_%VAR5%" "Description=''Map:Schlachtfeld Stuttgart (%VAR5%)" "%MAPDIR%\%MAPN32% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN32% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_%VAR5%" "Description=''Map:Tournament Arena (%VAR5%)" "%MAPDIR%\%MAPN33% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN33% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black3_%VAR5%" "Description=''Map:Barstow Badlands (%VAR5%)" "%MAPDIR%\%MAPN34% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN34% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black4_%VAR5%" "Description=''Map:Ground Zero (%VAR5%)" "%MAPDIR%\%MAPN35% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN35% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black5_%VAR5%" "Description=''Map:Small Town USA (%VAR5%)" "%MAPDIR%\%MAPN36% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN36% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black6_%VAR5%" "Description=''Map:Black's Big Battle (%VAR5%)" "%MAPDIR%\%MAPN37% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN37% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_%VAR5%" "Description=''Map:Tournament Tower (%VAR5%)" "%MAPDIR%\%MAPN38% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN38% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black8_%VAR5%" "Description=''Map:Tiber River Valley (%VAR5%)" "%MAPDIR%\%MAPN39% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN39% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black9_%VAR5%" "Description=''Map:Pipeline Problems (%VAR5%)" "%MAPDIR%\%MAPN40% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN40% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_chuck1_%VAR5%" "Description=''Map:Tournament Coastline (%VAR5%)" "%MAPDIR%\%MAPN41% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN41% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_%VAR5%" "Description=''Map:Riverside Rumble (%VAR5%)" "%MAPDIR%\%MAPN42% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN42% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_will1_%VAR5%" "Description=''Map:Tournament Rift (%VAR5%)" "%MAPDIR%\%MAPN43% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN43% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black1_%VAR5%" "Description=''Map:Unfair Advantage (%VAR5%)" "%MAPDIR%\%MAPN44% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN44% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black2_%VAR5%" "Description=''Map:Triple Threat (%VAR5%)" "%MAPDIR%\%MAPN45% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN45% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bass_%VAR5%" "Description=''Map:Downtown Dustbowl (%VAR5%)" "%MAPDIR%\%MAPN46% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN46% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bender_%VAR5%" "Description=''Map:The Battle for Middle Egypt (%VAR5%)" "%MAPDIR%\%MAPN47% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN47% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black1_%VAR5%" "Description=''Map:Crater of Carnage (%VAR5%)" "%MAPDIR%\%MAPN48% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN48% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black5_%VAR5%" "Description=''Map:Death Valley (%VAR5%)" "%MAPDIR%\%MAPN49% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN49% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black6_%VAR5%" "Description=''Map:Backwater Brawl (%VAR5%)" "%MAPDIR%\%MAPN50% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN50% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck1_%VAR5%" "Description=''Map:Coastline Chaos (%VAR5%)" "%MAPDIR%\%MAPN51% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN51% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck2_%VAR5%" "Description=''Map:Wrecktropolis (%VAR5%)" "%MAPDIR%\%MAPN52% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN52% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_rao_%VAR5%" "Description=''Map:Redzone Rampage (%VAR5%)" "%MAPDIR%\%MAPN53% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN53% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_ssmith_01_%VAR5%" "Description=''Map:Frontier Fracas (%VAR5%)" "%MAPDIR%\%MAPN54% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN54% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_5_black1_%VAR5%" "Description=''Map:Tiberium Gardens III (%VAR5%)" "%MAPDIR%\%MAPN55% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN55% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black1_%VAR5%" "Description=''Map:Black's Bigger Battle (%VAR5%)" "%MAPDIR%\%MAPN56% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN56% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black2_%VAR5%" "Description=''Map:Six Shooter Showdown (%VAR5%)" "%MAPDIR%\%MAPN57% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN57% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_hayes_%VAR5%" "Description=''Map:Dead Six (%VAR5%)" "%MAPDIR%\%MAPN58% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN58% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_bass_%VAR5%" "Description=''Map:The Rocktagon (%VAR5%)" "%MAPDIR%\%MAPN59% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN59% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_black1_%VAR5%" "Description=''Map:Bordertown Beatdown (%VAR5%)" "%MAPDIR%\%MAPN60% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN60% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_redzoned_%VAR5%" "Description=''Map:Decrepit Arena (%VAR5%)" "%MAPDIR%\%MAPN61% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN61% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_redzoned_%VAR5%" "Description=''Map:Blighted Tower (%VAR5%)" "%MAPDIR%\%MAPN62% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN62% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_redzoned_%VAR5%" "Description=''Map:Gunship Gauntlet (%VAR5%)" "%MAPDIR%\%MAPN63% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN63% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_b_%VAR5%" "Description=''Map:Ruined River (%VAR5%)" "%MAPDIR%\%MAPN64% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN64% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB01_3_%VAR5%" "Description=''Map:Cut 3player Map #1 (%VAR5%)" "%MAPDIR%\%MAPN65% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN65% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB02_3_%VAR5%" "Description=''Map:Cut 3player Map #2 (%VAR5%)" "%MAPDIR%\%MAPN66% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN66% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB03_3_%VAR5%" "Description=''Map:Cut 3player Map #3 (%VAR5%)" "%MAPDIR%\%MAPN67% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN67% (%VAR5%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB04_3_%VAR5%" "Description=''Map:Cut 3player Map #4 (%VAR5%)" "%MAPDIR%\%MAPN68% (%VAR5%)\map.xml" "%MAPDIR%\%MAPN68% (%VAR5%)\map_mod.xml"

"%SSR%" 0 "Description=''Map:bamap_aw01_04_%VAR6%" "Description=''Map:Seaport Smackdown (%VAR6%)" "%MAPDIR%\%MAPN01% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN01% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc01_4_%VAR6%" "Description=''Map:Grasslands Landgrab (%VAR6%)" "%MAPDIR%\%MAPN02% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN02% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc02_4_%VAR6%" "Description=''Map:Badlands (%VAR6%)" "%MAPDIR%\%MAPN03% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN03% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc03_3_%VAR6%" "Description=''Map:Desolation (%VAR6%)" "%MAPDIR%\%MAPN04% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN04% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc04_3_%VAR6%" "Description=''Map:End of the Line (%VAR6%)" "%MAPDIR%\%MAPN05% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN05% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_2_%VAR6%" "Description=''Map:Tournament Decision (%VAR6%)" "%MAPDIR%\%MAPN06% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN06% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_3_%VAR6%" "Description=''Map:Split Decision (%VAR6%)" "%MAPDIR%\%MAPN07% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN07% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc06_4_%VAR6%" "Description=''Map:Arid Remains (%VAR6%)" "%MAPDIR%\%MAPN08% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN08% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc07_4_%VAR6%" "Description=''Map:Mountains of Madness (%VAR6%)" "%MAPDIR%\%MAPN09% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN09% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc08_4_%VAR6%" "Description=''Map:Crosstown Conflict (%VAR6%)" "%MAPDIR%\%MAPN10% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN10% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc10_4_%VAR6%" "Description=''Map:Murderers Row (%VAR6%)" "%MAPDIR%\%MAPN11% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN11% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc11_4_%VAR6%" "Description=''Map:Empire City (%VAR6%)" "%MAPDIR%\%MAPN12% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN12% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew01_4_%VAR6%" "Description=''Map:Unsound Investment (%VAR6%)" "%MAPDIR%\%MAPN13% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN13% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew03_04_%VAR6%" "Description=''Map:Oasis Onslaught (%VAR6%)" "%MAPDIR%\%MAPN14% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN14% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew05_04_%VAR6%" "Description=''Map:Safety Nest (%VAR6%)" "%MAPDIR%\%MAPN15% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN15% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew06_04_%VAR6%" "Description=''Map:Shell Shocked (%VAR6%)" "%MAPDIR%\%MAPN16% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN16% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew07_04_%VAR6%" "Description=''Map:Urban Blight (%VAR6%)" "%MAPDIR%\%MAPN17% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN17% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew08_04_%VAR6%" "Description=''Map:Eastern Promises (%VAR6%)" "%MAPDIR%\%MAPN18% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN18% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew09_03_%VAR6%" "Description=''Map:Suburban Slaughterhouse (%VAR6%)" "%MAPDIR%\%MAPN19% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN19% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew10_06_%VAR6%" "Description=''Map:Tiberium Wasteland (%VAR6%)" "%MAPDIR%\%MAPN20% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN20% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew11_05_%VAR6%" "Description=''Map:Isthmus of Insanity (%VAR6%)" "%MAPDIR%\%MAPN21% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN21% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf01_4_%VAR6%" "Description=''Map:Dockside Devastation (%VAR6%)" "%MAPDIR%\%MAPN22% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN22% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf03_6_%VAR6%" "Description=''Map:Dark Waters (%VAR6%)" "%MAPDIR%\%MAPN23% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN23% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_kk03_3_%VAR6%" "Description=''Map:Tundra Triangle (%VAR6%)" "%MAPDIR%\%MAPN24% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN24% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_rh01_4_%VAR6%" "Description=''Map:Heaven and Hell (%VAR6%)" "%MAPDIR%\%MAPN25% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN25% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_sb01_4_%VAR6%" "Description=''Map:Missed Opportunity (%VAR6%)" "%MAPDIR%\%MAPN26% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN26% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:eamap_sb05_4_%VAR6%" "Description=''Map:Craters of Camden (%VAR6%)" "%MAPDIR%\%MAPN27% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN27% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_bass1_%VAR6%" "Description=''Map:Tournament Dustbowl (%VAR6%)" "%MAPDIR%\%MAPN28% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN28% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black1_%VAR6%" "Description=''Map:Tournament Desert Redux (%VAR6%)" "%MAPDIR%\%MAPN29% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN29% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black10_%VAR6%" "Description=''Map:Deadly Sertao (%VAR6%)" "%MAPDIR%\%MAPN30% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN30% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_%VAR6%" "Description=''Map:Top Gun (%VAR6%)" "%MAPDIR%\%MAPN31% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN31% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black12_%VAR6%" "Description=''Map:Schlachtfeld Stuttgart (%VAR6%)" "%MAPDIR%\%MAPN32% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN32% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_%VAR6%" "Description=''Map:Tournament Arena (%VAR6%)" "%MAPDIR%\%MAPN33% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN33% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black3_%VAR6%" "Description=''Map:Barstow Badlands (%VAR6%)" "%MAPDIR%\%MAPN34% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN34% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black4_%VAR6%" "Description=''Map:Ground Zero (%VAR6%)" "%MAPDIR%\%MAPN35% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN35% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black5_%VAR6%" "Description=''Map:Small Town USA (%VAR6%)" "%MAPDIR%\%MAPN36% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN36% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black6_%VAR6%" "Description=''Map:Black's Big Battle (%VAR6%)" "%MAPDIR%\%MAPN37% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN37% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_%VAR6%" "Description=''Map:Tournament Tower (%VAR6%)" "%MAPDIR%\%MAPN38% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN38% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black8_%VAR6%" "Description=''Map:Tiber River Valley (%VAR6%)" "%MAPDIR%\%MAPN39% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN39% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black9_%VAR6%" "Description=''Map:Pipeline Problems (%VAR6%)" "%MAPDIR%\%MAPN40% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN40% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_chuck1_%VAR6%" "Description=''Map:Tournament Coastline (%VAR6%)" "%MAPDIR%\%MAPN41% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN41% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_%VAR6%" "Description=''Map:Riverside Rumble (%VAR6%)" "%MAPDIR%\%MAPN42% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN42% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_will1_%VAR6%" "Description=''Map:Tournament Rift (%VAR6%)" "%MAPDIR%\%MAPN43% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN43% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black1_%VAR6%" "Description=''Map:Unfair Advantage (%VAR6%)" "%MAPDIR%\%MAPN44% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN44% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black2_%VAR6%" "Description=''Map:Triple Threat (%VAR6%)" "%MAPDIR%\%MAPN45% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN45% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bass_%VAR6%" "Description=''Map:Downtown Dustbowl (%VAR6%)" "%MAPDIR%\%MAPN46% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN46% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bender_%VAR6%" "Description=''Map:The Battle for Middle Egypt (%VAR6%)" "%MAPDIR%\%MAPN47% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN47% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black1_%VAR6%" "Description=''Map:Crater of Carnage (%VAR6%)" "%MAPDIR%\%MAPN48% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN48% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black5_%VAR6%" "Description=''Map:Death Valley (%VAR6%)" "%MAPDIR%\%MAPN49% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN49% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black6_%VAR6%" "Description=''Map:Backwater Brawl (%VAR6%)" "%MAPDIR%\%MAPN50% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN50% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck1_%VAR6%" "Description=''Map:Coastline Chaos (%VAR6%)" "%MAPDIR%\%MAPN51% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN51% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck2_%VAR6%" "Description=''Map:Wrecktropolis (%VAR6%)" "%MAPDIR%\%MAPN52% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN52% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_rao_%VAR6%" "Description=''Map:Redzone Rampage (%VAR6%)" "%MAPDIR%\%MAPN53% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN53% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_ssmith_01_%VAR6%" "Description=''Map:Frontier Fracas (%VAR6%)" "%MAPDIR%\%MAPN54% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN54% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_5_black1_%VAR6%" "Description=''Map:Tiberium Gardens III (%VAR6%)" "%MAPDIR%\%MAPN55% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN55% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black1_%VAR6%" "Description=''Map:Black's Bigger Battle (%VAR6%)" "%MAPDIR%\%MAPN56% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN56% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black2_%VAR6%" "Description=''Map:Six Shooter Showdown (%VAR6%)" "%MAPDIR%\%MAPN57% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN57% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_hayes_%VAR6%" "Description=''Map:Dead Six (%VAR6%)" "%MAPDIR%\%MAPN58% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN58% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_bass_%VAR6%" "Description=''Map:The Rocktagon (%VAR6%)" "%MAPDIR%\%MAPN59% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN59% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_black1_%VAR6%" "Description=''Map:Bordertown Beatdown (%VAR6%)" "%MAPDIR%\%MAPN60% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN60% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_redzoned_%VAR6%" "Description=''Map:Decrepit Arena (%VAR6%)" "%MAPDIR%\%MAPN61% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN61% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_redzoned_%VAR6%" "Description=''Map:Blighted Tower (%VAR6%)" "%MAPDIR%\%MAPN62% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN62% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_redzoned_%VAR6%" "Description=''Map:Gunship Gauntlet (%VAR6%)" "%MAPDIR%\%MAPN63% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN63% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_b_%VAR6%" "Description=''Map:Ruined River (%VAR6%)" "%MAPDIR%\%MAPN64% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN64% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB01_3_%VAR6%" "Description=''Map:Cut 3player Map #1 (%VAR6%)" "%MAPDIR%\%MAPN65% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN65% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB02_3_%VAR6%" "Description=''Map:Cut 3player Map #2 (%VAR6%)" "%MAPDIR%\%MAPN66% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN66% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB03_3_%VAR6%" "Description=''Map:Cut 3player Map #3 (%VAR6%)" "%MAPDIR%\%MAPN67% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN67% (%VAR6%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB04_3_%VAR6%" "Description=''Map:Cut 3player Map #4 (%VAR6%)" "%MAPDIR%\%MAPN68% (%VAR6%)\map.xml" "%MAPDIR%\%MAPN68% (%VAR6%)\map_mod.xml"

"%SSR%" 0 "Description=''Map:bamap_aw01_04_%VAR7%" "Description=''Map:Seaport Smackdown (%VAR7%)" "%MAPDIR%\%MAPN01% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN01% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc01_4_%VAR7%" "Description=''Map:Grasslands Landgrab (%VAR7%)" "%MAPDIR%\%MAPN02% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN02% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc02_4_%VAR7%" "Description=''Map:Badlands (%VAR7%)" "%MAPDIR%\%MAPN03% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN03% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc03_3_%VAR7%" "Description=''Map:Desolation (%VAR7%)" "%MAPDIR%\%MAPN04% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN04% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc04_3_%VAR7%" "Description=''Map:End of the Line (%VAR7%)" "%MAPDIR%\%MAPN05% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN05% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_2_%VAR7%" "Description=''Map:Tournament Decision (%VAR7%)" "%MAPDIR%\%MAPN06% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN06% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc05_3_%VAR7%" "Description=''Map:Split Decision (%VAR7%)" "%MAPDIR%\%MAPN07% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN07% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc06_4_%VAR7%" "Description=''Map:Arid Remains (%VAR7%)" "%MAPDIR%\%MAPN08% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN08% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc07_4_%VAR7%" "Description=''Map:Mountains of Madness (%VAR7%)" "%MAPDIR%\%MAPN09% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN09% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc08_4_%VAR7%" "Description=''Map:Crosstown Conflict (%VAR7%)" "%MAPDIR%\%MAPN10% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN10% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc10_4_%VAR7%" "Description=''Map:Murderers Row (%VAR7%)" "%MAPDIR%\%MAPN11% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN11% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_dc11_4_%VAR7%" "Description=''Map:Empire City (%VAR7%)" "%MAPDIR%\%MAPN12% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN12% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew01_4_%VAR7%" "Description=''Map:Unsound Investment (%VAR7%)" "%MAPDIR%\%MAPN13% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN13% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew03_04_%VAR7%" "Description=''Map:Oasis Onslaught (%VAR7%)" "%MAPDIR%\%MAPN14% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN14% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew05_04_%VAR7%" "Description=''Map:Safety Nest (%VAR7%)" "%MAPDIR%\%MAPN15% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN15% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew06_04_%VAR7%" "Description=''Map:Shell Shocked (%VAR7%)" "%MAPDIR%\%MAPN16% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN16% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew07_04_%VAR7%" "Description=''Map:Urban Blight (%VAR7%)" "%MAPDIR%\%MAPN17% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN17% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew08_04_%VAR7%" "Description=''Map:Eastern Promises (%VAR7%)" "%MAPDIR%\%MAPN18% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN18% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew09_03_%VAR7%" "Description=''Map:Suburban Slaughterhouse (%VAR7%)" "%MAPDIR%\%MAPN19% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN19% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew10_06_%VAR7%" "Description=''Map:Tiberium Wasteland (%VAR7%)" "%MAPDIR%\%MAPN20% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN20% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_ew11_05_%VAR7%" "Description=''Map:Isthmus of Insanity (%VAR7%)" "%MAPDIR%\%MAPN21% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN21% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf01_4_%VAR7%" "Description=''Map:Dockside Devastation (%VAR7%)" "%MAPDIR%\%MAPN22% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN22% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_jf03_6_%VAR7%" "Description=''Map:Dark Waters (%VAR7%)" "%MAPDIR%\%MAPN23% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN23% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_kk03_3_%VAR7%" "Description=''Map:Tundra Triangle (%VAR7%)" "%MAPDIR%\%MAPN24% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN24% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_rh01_4_%VAR7%" "Description=''Map:Heaven and Hell (%VAR7%)" "%MAPDIR%\%MAPN25% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN25% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:bamap_sb01_4_%VAR7%" "Description=''Map:Missed Opportunity (%VAR7%)" "%MAPDIR%\%MAPN26% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN26% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:eamap_sb05_4_%VAR7%" "Description=''Map:Craters of Camden (%VAR7%)" "%MAPDIR%\%MAPN27% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN27% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_bass1_%VAR7%" "Description=''Map:Tournament Dustbowl (%VAR7%)" "%MAPDIR%\%MAPN28% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN28% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black1_%VAR7%" "Description=''Map:Tournament Desert Redux (%VAR7%)" "%MAPDIR%\%MAPN29% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN29% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black10_%VAR7%" "Description=''Map:Deadly Sertao (%VAR7%)" "%MAPDIR%\%MAPN30% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN30% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_%VAR7%" "Description=''Map:Top Gun (%VAR7%)" "%MAPDIR%\%MAPN31% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN31% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black12_%VAR7%" "Description=''Map:Schlachtfeld Stuttgart (%VAR7%)" "%MAPDIR%\%MAPN32% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN32% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_%VAR7%" "Description=''Map:Tournament Arena (%VAR7%)" "%MAPDIR%\%MAPN33% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN33% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black3_%VAR7%" "Description=''Map:Barstow Badlands (%VAR7%)" "%MAPDIR%\%MAPN34% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN34% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black4_%VAR7%" "Description=''Map:Ground Zero (%VAR7%)" "%MAPDIR%\%MAPN35% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN35% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black5_%VAR7%" "Description=''Map:Small Town USA (%VAR7%)" "%MAPDIR%\%MAPN36% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN36% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black6_%VAR7%" "Description=''Map:Black's Big Battle (%VAR7%)" "%MAPDIR%\%MAPN37% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN37% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_%VAR7%" "Description=''Map:Tournament Tower (%VAR7%)" "%MAPDIR%\%MAPN38% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN38% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black8_%VAR7%" "Description=''Map:Tiber River Valley (%VAR7%)" "%MAPDIR%\%MAPN39% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN39% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black9_%VAR7%" "Description=''Map:Pipeline Problems (%VAR7%)" "%MAPDIR%\%MAPN40% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN40% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_chuck1_%VAR7%" "Description=''Map:Tournament Coastline (%VAR7%)" "%MAPDIR%\%MAPN41% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN41% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_%VAR7%" "Description=''Map:Riverside Rumble (%VAR7%)" "%MAPDIR%\%MAPN42% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN42% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_will1_%VAR7%" "Description=''Map:Tournament Rift (%VAR7%)" "%MAPDIR%\%MAPN43% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN43% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black1_%VAR7%" "Description=''Map:Unfair Advantage (%VAR7%)" "%MAPDIR%\%MAPN44% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN44% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_3_black2_%VAR7%" "Description=''Map:Triple Threat (%VAR7%)" "%MAPDIR%\%MAPN45% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN45% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bass_%VAR7%" "Description=''Map:Downtown Dustbowl (%VAR7%)" "%MAPDIR%\%MAPN46% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN46% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_bender_%VAR7%" "Description=''Map:The Battle for Middle Egypt (%VAR7%)" "%MAPDIR%\%MAPN47% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN47% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black1_%VAR7%" "Description=''Map:Crater of Carnage (%VAR7%)" "%MAPDIR%\%MAPN48% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN48% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black5_%VAR7%" "Description=''Map:Death Valley (%VAR7%)" "%MAPDIR%\%MAPN49% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN49% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_black6_%VAR7%" "Description=''Map:Backwater Brawl (%VAR7%)" "%MAPDIR%\%MAPN50% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN50% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck1_%VAR7%" "Description=''Map:Coastline Chaos (%VAR7%)" "%MAPDIR%\%MAPN51% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN51% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_chuck2_%VAR7%" "Description=''Map:Wrecktropolis (%VAR7%)" "%MAPDIR%\%MAPN52% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN52% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_rao_%VAR7%" "Description=''Map:Redzone Rampage (%VAR7%)" "%MAPDIR%\%MAPN53% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN53% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_4_ssmith_01_%VAR7%" "Description=''Map:Frontier Fracas (%VAR7%)" "%MAPDIR%\%MAPN54% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN54% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_5_black1_%VAR7%" "Description=''Map:Tiberium Gardens III (%VAR7%)" "%MAPDIR%\%MAPN55% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN55% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black1_%VAR7%" "Description=''Map:Black's Bigger Battle (%VAR7%)" "%MAPDIR%\%MAPN56% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN56% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_black2_%VAR7%" "Description=''Map:Six Shooter Showdown (%VAR7%)" "%MAPDIR%\%MAPN57% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN57% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_6_hayes_%VAR7%" "Description=''Map:Dead Six (%VAR7%)" "%MAPDIR%\%MAPN58% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN58% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_bass_%VAR7%" "Description=''Map:The Rocktagon (%VAR7%)" "%MAPDIR%\%MAPN59% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN59% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_8_black1_%VAR7%" "Description=''Map:Bordertown Beatdown (%VAR7%)" "%MAPDIR%\%MAPN60% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN60% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black2_redzoned_%VAR7%" "Description=''Map:Decrepit Arena (%VAR7%)" "%MAPDIR%\%MAPN61% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN61% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black7_redzoned_%VAR7%" "Description=''Map:Blighted Tower (%VAR7%)" "%MAPDIR%\%MAPN62% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN62% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_black11_redzoned_%VAR7%" "Description=''Map:Gunship Gauntlet (%VAR7%)" "%MAPDIR%\%MAPN63% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN63% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:map_mp_2_simon_b_%VAR7%" "Description=''Map:Ruined River (%VAR7%)" "%MAPDIR%\%MAPN64% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN64% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB01_3_%VAR7%" "Description=''Map:Cut 3player Map #1 (%VAR7%)" "%MAPDIR%\%MAPN65% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN65% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB02_3_%VAR7%" "Description=''Map:Cut 3player Map #2 (%VAR7%)" "%MAPDIR%\%MAPN66% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN66% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB03_3_%VAR7%" "Description=''Map:Cut 3player Map #3 (%VAR7%)" "%MAPDIR%\%MAPN67% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN67% (%VAR7%)\map_mod.xml"
"%SSR%" 0 "Description=''Map:EAMAP_SB04_3_%VAR7%" "Description=''Map:Cut 3player Map #4 (%VAR7%)" "%MAPDIR%\%MAPN68% (%VAR7%)\map.xml" "%MAPDIR%\%MAPN68% (%VAR7%)\map_mod.xml"

PAUSE